### ISSUE TITLE
Update Naraka: Bladepoint

### ISSUE THREAD

**Issue by Th1ngP3rs0n** [Starz0r/AreWeAntiCheatYet#1001]
### Game Title

Naraka: Bladepoint

### Status of the Anti-Cheat

👍 Running

### Tinkering Steps

I don't know what's up with the anti-cheat, but it seems to be working out of the box now.

### Proof of Mention

https://www.protondb.com/app/1203220

**Comment by Etaash-mathamsetty** [comment]
it's also been working for the past month it seems like, but we can never know, so it's probably best to keep it as "running"
