### ISSUE TITLE
Update Marauders

### ISSUE THREAD

**Issue by YourHuckleberry** [Starz0r/AreWeAntiCheatYet#1019]
### Game Title

Marauders

### Status of the Anti-Cheat

😥 Broken

### Tinkering Steps

EAC became broken back in November during an update.  Still not working with newest December update.
Please change to Broken.

### Proof of Mention

https://www.protondb.com/app/1789480

**Comment by MystikReasons** [comment]
+1 from me, ProtonDB is also full of negative reports since the Health update

**Comment by MystikReasons** [comment]
+1 from me
