### ISSUE TITLE
DBD no longer works with workaround 

### ISSUE THREAD

**Issue by roope242** [Starz0r/AreWeAntiCheatYet#1026]
### Game Title

Dead by Daylight 

### Status of the Anti-Cheat

🕧 Planned

### Tinkering Steps

The workaround worked for a while but is no longer working. This was confirmed in the same thread which seems to have been removed by now.

### Proof of Mention

https://forum.deadbydaylight.com/en/discussion/comment/3265222/

**Comment by Curve** [comment]
https://github.com/Starz0r/AreWeAntiCheatYet/issues/971

This was the previous discussion on the subject, someone else also reported it as not working even though it was.

Before changing the status again I'd like to make sure that it's not just "your system" and that all workaround steps were followed correctly

**Comment by Etaash-mathamsetty** [comment]
the game is still functioning for me, just played as survivor, no disconnect issues

**Comment by roope242** [comment]
Interesting, I will have to re-test this with my machine then, my apologies.

**Comment by FriederHannenheim** [comment]
I'm on steam. I tried playing with the workaround. The game starts and lets me load into a party but when it is loading into the match I get booted and the game says there's a connection error

**Comment by Curve** [comment]
> I'm on steam. I tried playing with the workaround. The game starts and lets me load into a party but when it is loading into the match I get booted and the game says there's a connection error

As the workaround states, the game only seems to work when played through epic games

**Comment by zookee1** [comment]
Did not work for me on the steam version.

I tried all workarounds that are floating around for some time now with non of them working. I can start the game, find a match and start loading into it. After a while the loading stops and I get kicked with an Error 500.

**Comment by Curve** [comment]
> Did not work for me on the steam version.
> 
> I tried all workarounds that are floating around for some time now with non of them working. I can start the game, find a match and start loading into it. After a while the loading stops and I get kicked with an Error 500.

As far as I know, and as remarked on the website, it currently only works with the epic games version

**Comment by Gustash** [comment]
Yes, this only works on the Epic Games version for now, and has been noted on the website. It will disconnect with 500 on the Steam version.

**Comment by Curve** [comment]
I'll close this issue for now, as it works with the epic games version, as reflected in the games' notes on the website
