### ISSUE TITLE
Arma 3 (Update)

### ISSUE THREAD

**Issue by Vinjul1704** [Starz0r/AreWeAntiCheatYet#103]
### Game Title

Arma 3

### Game Website

https://arma3.com/

### Anti-Cheat Software

BattlEye

### Status of the Anti-Cheat

🎉 Confirmed

### Proof of Mention

https://media.discordapp.net/attachments/239344443503804416/891805930612723712/unknown.png

**Comment by Vinjul1704** [comment]
This is an update to the entry for Arma 3. It was confirmed by one of the devs on the official Discord that there is legitimate interest in enabling Wine/Proton compatibility for BE as soon as it becomes available, with further comments along the lines of "why would a developer not want it?".

The message can be found via this link: https://discord.com/channels/105462288051380224/105467328782692352/891031083053879306
You need to be on the official Discord for the link to work: https://discord.com/invite/arma

**Comment by Starz0r** [comment]
For prosperity’ sake, in case the OP edits their post.

Proof: media.discordapp.net/attachments/239344443503804416/891805930612723712/unknown.png
Statement: discord.com/channels/105462288051380224/105467328782692352/891031083053879306 in discord.com/invite/arma

**Comment by ShaunTheQuietGamer** [comment]
> 
> 
> of course it's not an official statement, he's a fucking furry
> 
> It's obviously a joke for the ones who don't get it

Obviously a really bad joke. Nice job insulting one of the only devs that seems to actually be working on bugfixes and improvments these days.

**Comment by ClemGlacee** [comment]
> > of course it's not an official statement, he's a fucking furry
> > It's obviously a joke for the ones who don't get it
> 
> Obviously a really bad joke. Nice job insulting one of the only devs that seems to actually be working on bugfixes and improvements these days.
> 
> Edit: Spelling

Ok dude

**Comment by endigma** [comment]
> Obviously a really bad joke. Nice job insulting one of the only devs that seems to actually be working on bugfixes and improvements these days.

Dedmen maintains one of the most restrictively licensed mods and permabans people for swearing on the Arma 3 discord, wouldn't peg him as a core contributor.
