### ISSUE TITLE
Error on Safari/Webkit

### ISSUE THREAD

**Issue by Bougy9** [Starz0r/AreWeAntiCheatYet#1035]
Impossible to use the website on Safari/Webkit , when it load the website it display : "Application error: a client-side exception has occured (see browser console for more information) "
![IMG_2350](https://user-images.githubusercontent.com/43933872/208995610-e3875f4f-0aa1-4068-9274-c19db05de27f.PNG)
![IMG_2351](https://user-images.githubusercontent.com/43933872/208995615-5755785f-1e8b-472b-a9c7-4eff79280839.PNG)
![IMG_2352](https://user-images.githubusercontent.com/43933872/208995618-c82adaec-ba04-4d37-8f6c-da5f5fd18b7c.PNG)

**Comment by Bougy9** [comment]
nope it does the same thing

**Comment by Curve** [comment]
Works for me on latest iOS with Safari, I suspect you're stuck on an invalid update cache (probably my fault, sorry) - But good to know there are still code-paths that can error, I'll have a look later to make it possible to load the site regardless of an invalid update cache

**Comment by pbogut** [comment]
I have same error in [qutebrowser](https://github.com/qutebrowser/qutebrowser) it usese QTWebEngine for page rendering. It's nothing new, it started to happening with redesign in place. I was to lazy to create an issue and just dissabled JS for this website.

**Comment by Curve** [comment]
The browser engine doesn't matter here, it's probably an issue with how we handle the game changes, I may get to refactoring later today

**Comment by Curve** [comment]
> Well, its usage of [Array.at](https://caniuse.com/?search=array.at) function, it is not available everywhere. QTWebEngine reports version 87 of chrome, and it was not supported in that version. @Bougy9  probably has older version of Safari.
> 
> If I implement this function myself and inject it with greassmonkey it works fine.
> ```js
> Array.prototype.at = function(index) {
>   if (index < 0) {
>     index = this.length + index
>   }
>   return this[index];
> }
> ```
> 
> I think it is used in 3 places, always to get last element of an array. I guess you could replace it with something like `updates[updates.length-1]`.

Holy shoot I wasn't aware that Array.at isn't widely supported, will change it later, thanks for the info!

**Comment by Curve** [comment]
I pushed some changes to fix this, you can check if `https://starz0r.github.io/AreWeAntiCheatYet/` works for you (will be updated sooner than the actual website)

**Comment by Bougy9** [comment]
ok, it work now in the actual website, closing issue
