### ISSUE TITLE
Search query string

### ISSUE THREAD

**Issue by ChildishGiant** [Starz0r/AreWeAntiCheatYet#1048]
It'd be great if `https://areweanticheatyet.com/?q=%s` could prefill the search field so that it can be added as a search engine in browsers. Adding an [OpenSearch XML](https://developer.mozilla.org/en-US/docs/Web/OpenSearch) would let browsers know that this exists.

**Comment by Curve** [comment]
Great idea!
I'll have to look into it ^^

**Comment by ChildishGiant** [comment]
I do a similar thing on my webapp cloverleaf, which is all JS. https://github.com/cloverleaf/web/blob/ed72c36ffc4eb9d14af14f60353a77edec2f646c/src/main.js#L108

**Comment by Curve** [comment]
Alright, I've add basic support for query param parsing, haven't looked into OpenSearchXML yet though
