### ISSUE TITLE
Add it to the list if you want? I think?

### ISSUE THREAD

**Issue by oddsito** [Starz0r/AreWeAntiCheatYet#1056]
### Game Title

PUBG - Battlegrounds

### Game Website

https://na.battlegrounds.pubg.com/

### Anti-Cheat Software

Other

### Status of the Anti-Cheat

🚫 Denied

### Proof of Mention

https://www.reddit.com/r/linux_gaming/comments/s2c3i6/pubg_on_linux/

**Comment by Curve** [comment]
PUBG is already on the list?
