### ISSUE TITLE
Update Squad

### ISSUE THREAD

**Issue by zocker-160** [Starz0r/AreWeAntiCheatYet#1084]
### Game Title

Squad

### Status of the Anti-Cheat

👍 Running

### Tinkering Steps

The mentioned workaround is no longer required when doing a fresh install and using Proton Experimental.
The workaround can actually cause problems and make the game not work.

### Proof of Mention

https://github.com/ValveSoftware/Proton/issues/938
https://github.com/ValveSoftware/Proton/issues/938#issuecomment-1381029311

**Comment by Etaash-mathamsetty** [comment]
I think it should be updated to supported then
