### ISSUE TITLE
The Division 2

### ISSUE THREAD

**Issue by Spectrism** [Starz0r/AreWeAntiCheatYet#1086]
### Game Title

The Division 2

### Status of the Anti-Cheat

⭐ Supported

### Tinkering Steps

Easy Anti-Cheat runtime is probably required, but aside from that, no tinkering is needed.

### Proof of Mention

https://www.protondb.com/app/2221490
https://steamcommunity.com/app/2221490/eventcomments/3765606379488848370/
https://steamdb.info/depot/2221491/history/?changeid=M:1578087515434494402
https://www.gamingonlinux.com/2023/01/ubisoft-fixed-the-division-2-on-steam-deck-and-linux-desktop/

**Comment by DeltaTimo** [comment]
I second this. I had to set the kernel parameter `net.ipv4.tcp_mtu_probing=1` for Ubisoft Connect to be able to correctly log in and get past "Initializing." Other than that, EAC worked out of the box now.

**Comment by gibarel1** [comment]
on uplay [this](https://www.reddit.com/r/linux_gaming/comments/10gag7d/division_2_uplay_version_working_on_wine/) workaround might be needed

**Comment by Curve** [comment]
Great News!

Sorry I didn't update yet, will try tomorrow but PRs are also always welcome ^^
