### ISSUE TITLE
Update The Division 2

### ISSUE THREAD

**Issue by corpeder** [Starz0r/AreWeAntiCheatYet#1092]
### Game Title

The Division 2

### Status of the Anti-Cheat

⭐ Supported

### Tinkering Steps

If purchased on steam just make sure you have the proper anticheat runtime installed in tools as well.

If playing directly on Ubisoft Connect, it seems they have not updated that one yet with the proper files. Workaround is possible.

[https://www.reddit.com/r/SteamDeck/comments/10fsva1/how_to_get_the_division_2_ubisoft_connect_to_work/?utm_source=share&utm_medium=ios_app&utm_name=iossmf](url)

### Proof of Mention

https://www.reddit.com/r/linux_gaming/comments/10fgkff/the_division_2_is_now_playable_on_steam_deck_and/

**Comment by Curve** [comment]
Division 2 is already listed as supported.
