### ISSUE TITLE
Rising Storm 2

### ISSUE THREAD

**Issue by eg-z** [Starz0r/AreWeAntiCheatYet#11]
### Game Title

Rising Storm 2

### Game Website

https://www.epicgames.com/store/en-US/p/rising-storm-2-vietnam

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention

N/A

**Comment by plastic-fork** [comment]
Wont ever work because their EAC version is old, they don't use the EOS version.
Source: https://forums.tripwireinteractive.com/index.php?threads/linux-support-for-easy-anticheat.2329543/post-2350472

However, you can play on EAC servers if you force proton 6.3-7
