### ISSUE TITLE
Update Hunt showdown

### ISSUE THREAD

**Issue by gibarel1** [Starz0r/AreWeAntiCheatYet#1137]
### Game Title

Hunt Shouwdow

### Status of the Anti-Cheat

👍 Running

### Tinkering Steps

Install EAC runtime

Haven't confirmed it myself yet but there has been at least 3 people in th thread that claimed it worked. no official statement yet, therefore "Running" and not "Supported"

### Proof of Mention

https://www.reddit.com/r/linux_gaming/comments/112u4az/ladies_and_gentlemen_i_played_hunt_showdown_on

**Comment by Curve** [comment]
Will update the status once I've finished the website re-design & re-work ^^

**Comment by PoorPocketsMcNewHold** [comment]
Further working reports : [https://steamcommunity.com/app/594650/discussions/8/2954914688105803176/?ctp=57#c3780245614655492909](https://steamcommunity.com/app/594650/discussions/8/2954914688105803176/?ctp=57#c3780245614655492909)

And an article https://www.gamingonlinux.com/2023/02/hunt-showdown-added-easy-anti-cheat-for-steam-deck-linux/
