### ISSUE TITLE
Warhammer 40,000: Space Marine

### ISSUE THREAD

**Issue by Zlopez** [Starz0r/AreWeAntiCheatYet#114]
### Game Title

Warhammer 40,000: Space Marine

### Game Website

https://store.steampowered.com/app/55150

### Anti-Cheat Software

Other

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention

N/A

**Comment by Starz0r** [comment]
Yeah, this is a single player game with no multiplayer component. Go see https://github.com/ValveSoftware/Proton/issues/934 if you need support for getting the game to work.
