### ISSUE TITLE
Update Paladins

### ISSUE THREAD

**Issue by LouisMarotta** [Starz0r/AreWeAntiCheatYet#1150]
### Game Title

Paladins

### Status of the Anti-Cheat

😥 Broken

### Tinkering Steps

Dev response on reddit says that it's currently not a possibility

### Proof of Mention

https://www.reddit.com/r/paladinsgame/comments/110mcuf/with_em_striving_to_do_better_how_about_some/j8g2nam/

**Comment by Curve** [comment]
Changed in 6ccc80ffe7edfb3796695774ec6aff93da181291, accidentally referenced the wrong issue
