### ISSUE TITLE
Update Totally Accurate Battlegrounds

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [Starz0r/AreWeAntiCheatYet#1154]
### Game Title

Totally Accurate Battlegrounds

### Status of the Anti-Cheat

⭐ Supported

### Tinkering Steps

the game now supports linux because EQU8 is dead/nearly dead and now they have switched to EAC, expect all EQU8 games that still are getting updates to be affected (except splitgate). 

Even though no devs are working on it, they still updated the game to make sure we can continue playing it, gotta love to see it. 

### Proof of Mention

https://store.steampowered.com/news/app/823130/view/3653017658282026315?l=english

**Comment by JoneKone** [comment]
https://www.gamingonlinux.com/2023/02/totally-accurate-battlegrounds-now-works-on-linux-and-steam-deck/

**Comment by Curve** [comment]
Thanks for the good references!

Will update soon
