### ISSUE TITLE
Update EAC and add Proton Support

### ISSUE THREAD

**Issue by TVBotPC** [Starz0r/AreWeAntiCheatYet#1185]
### Game Title

Dead by Daylight

### Status of the Anti-Cheat

🚫 Denied

### Tinkering Steps

Right now to play DBD on Steam Deck or Linux you have to use Heroic Launcher and use Epic Games version but thats for Epic Games not Steam and its probably laggy if BHVR Does this Updates EAC and add Proton Support not only will the cheating go down less but Linux and Steam Deck Users can play Dead by Daylight so plz BHVR

### Proof of Mention

https://www.reddit.com/r/SteamDeck/comments/109vzu2/dbd_on_steam_deck_through_heroic_games_launcher/

**Comment by Curve** [comment]
1. This is not denied
2. We explicitly state that it works with Heroic only, so I reckon running perfectly reflects that
