### ISSUE TITLE
Valorant

### ISSUE THREAD

**Issue by delta-whiplash** [Starz0r/AreWeAntiCheatYet#119]
### Game Title

Valorant

### Game Website

https://playvalorant.com/

### Anti-Cheat Software

Other

### Status of the Anti-Cheat

🚫 Denied

### Proof of Mention

https://www.reddit.com/r/linux_gaming/comments/j0p46x/is_there_any_way_to_play_valorant_on_linux/

**Comment by Starz0r** [comment]
Developers haven't made an official statement on the Steam Deck yet, so I'm going to consider this invalid for the time being.
