### ISSUE TITLE
Font size on iPhone

### ISSUE THREAD

**Issue by MathiewMay** [Starz0r/AreWeAntiCheatYet#122]
I think the font size on mobile should be reduced to fit more games on the display and better alignment ![image](https://user-images.githubusercontent.com/79875811/136806995-2cea6da5-b7ab-4360-a62e-c58ef89bc4a8.png)

**Comment by dedo1911** [comment]
Same is from desktop, it's just too big.

I would remove this font-size increase here: https://github.com/Starz0r/AreWeAntiCheatYet/blob/2426bc621270072c6a9824f0fac708d39b3b8988/src/layouts/default.vue#L29
