### ISSUE TITLE
Tom Clancy's Rainbow Six Siege

### ISSUE THREAD

**Issue by enzod-lgtm** [Starz0r/AreWeAntiCheatYet#131]
### Game Title

Tom Clancy's Rainbow Six Siege

### Game Website

ubisoft.com/en-us/game/rainbow-six/siege

### Anti-Cheat Software

BattlEye

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention

N/A

**Comment by Starz0r** [comment]
Thank you for the submission!

It seems that Rainbow Six: Siege was already on the list prior to this ticket.
