### ISSUE TITLE
[Feature] email notifications

### ISSUE THREAD

**Issue by Trollwut** [Starz0r/AreWeAntiCheatYet#133]
Hey there!

Any chance on implementing an (email) notification feature?

For me it would be enough to get a mail if a game's status change.

**Comment by Lightjohn** [comment]
Even if I like the idea of suscribe I would prefer to be alerted only on new working games.
Maybe a rss files would be simpler? No big setup only, xml files somewhere and update/generate it automatically?

**Comment by Curve** [comment]
> Even if I like the idea of suscribe I would prefer to be alerted only on new working games.
> Maybe a rss files would be simpler? No big setup only, xml files somewhere and update/generate it automatically? 

That sounds really cool
With the redesign this should be fairly simple to generate at build time and place in the repo

**Comment by Curve** [comment]
I've added an rss-feed (currently it is only accessible through `raw.githubusercontent` but depending on if we change the deployment method that may change).

The link to the rss feed is:
https://raw.githubusercontent.com/Starz0r/AreWeAntiCheatYet/rss/feed.rss

**Comment by Curve** [comment]
I've properly implemented the rss-feed now, see the readme for more information!
