### ISSUE TITLE
Paladins

### ISSUE THREAD

**Issue by akatsukilevi** [Starz0r/AreWeAntiCheatYet#14]
### Game Title

Paladins: Champions of the Realm

### Game Website

https://www.paladins.com/

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

⭐ Enabled

### Proof of Mention

https://steamcommunity.com/app/444090/discussions/0/2956040588019127480/

**Comment by akatsukilevi** [comment]
NOTE: I know the game is already on the list, yet with the 'Uncomfirmed' status. I can personally confirm it is working, as I was playing it yesterday via Steam on Fedora 34, running kernel 5.14.9-200.fc34.x86_64 and Proton-GE 6.18-GE-2 (build 1632654100)

**Comment by Starz0r** [comment]
Not exactly sure, it should be under the GNU/Linux equivalent for Windows's `AppData`. Should be in a folder called `EasyAntiCheat`, and the file is `loader.log`.

**Comment by akatsukilevi** [comment]
Give me one minute, literally hoped on a match to test it up and make sure it is working

**Comment by akatsukilevi** [comment]
Just finished the match, absolutely no issues(aside from me sucking at the game XD)

![Screenshot from 2021-10-10 17-50-16](https://user-images.githubusercontent.com/37668033/136712969-154a59f2-c96c-48f1-b82d-bd321127f13e.png)
![Screenshot from 2021-10-10 17-52-21](https://user-images.githubusercontent.com/37668033/136712970-fc66c3c8-8bb2-4ac1-8191-e4894584ef93.png)
![Screenshot from 2021-10-10 17-53-06](https://user-images.githubusercontent.com/37668033/136712971-8f102040-11d7-4466-bd53-726ad8541328.png)
![Screenshot from 2021-10-10 17-54-53](https://user-images.githubusercontent.com/37668033/136712972-920959e5-2f13-476c-bf86-5de8c0351311.png)
![Screenshot from 2021-10-10 17-57-48](https://user-images.githubusercontent.com/37668033/136712973-dba8c4ef-9a87-49f0-8b97-d0c72432c74f.png)
![Screenshot from 2021-10-10 18-04-20](https://user-images.githubusercontent.com/37668033/136712974-f7276545-c2fa-4977-886b-a9dc9206b86b.png)
![Screenshot from 2021-10-10 18-04-28](https://user-images.githubusercontent.com/37668033/136712975-e53db141-0de3-41e9-9212-cee6c5f75096.png)

**Comment by Starz0r** [comment]
I need the `loader.log` file to be 100% sure. You can play some EAC games if the implementation is poorly applied. If there is an error in there, or if it's successful, that file would tell me.

**Comment by akatsukilevi** [comment]
Had forgot to attach, for reference this file I found in Paladins > Binaries > Win64 > loader.log
Uploaded to drive 'cause Github didn't wanted to attach it(?)
https://drive.google.com/file/d/14IqPCKRPoxOJZsyB5x1EuvDnOW7yu_pb/view?usp=sharing

**Comment by Starz0r** [comment]
Okay, after analyzing the files, I've come to the conclusion that the Paladins EAC implementation is actually poorly applied. The binary for the anti-cheat never starts downloading and stalls at 0%, meaning that the anti-cheat is never injected. Regardless of what `gamelauncher.log` says, `loader.log` is the only source of truth, and so far it looks like it doesn't actually work.

Despite the game opening, and being able to play matches, personally, I'd advise you to further discontinue playing this game under GNU/Linux until they actually enable support. Right now, you're playing with fire, and there is no tell whether they would allow this to continue to go undetected or not. But I'll leave that up to whether to value your Hi-Rez account or not.

If you want to see what the log file should look like, here are three examples from my own play session from randomly chosen games (with some information redacted), playing natively on a bare-metal Windows 10 machine. Notice how all of them have no mention, or reference of an error? This is what it should look like when you launch one of these games, any mention of an error in the `loader.log`, and it most likely isn't working as the developers intended.

**Comment by akatsukilevi** [comment]
Sad, thought it was properly working
Hopefully Hi-Rez enable compatibility soon
And about this Issue ticket, I think it can be properly closed? Later on if there's a update or development of Paladins situation, it can be re-opened

**Comment by MrNessuno** [comment]
> Okay, after analyzing the files, I've come to the conclusion that the Paladins EAC implementation is actually poorly applied. The binary for the anti-cheat never starts downloading and stalls at 0%, meaning that the anti-cheat is never injected. Regardless of what `gamelauncher.log` says, `loader.log` is the only source of truth, and so far it looks like it doesn't actually work.
> 
> Despite the game opening, and being able to play matches, personally, I'd advise you to further discontinue playing this game under GNU/Linux until they actually enable support. Right now, you're playing with fire, and there is no telling whether they would allow this to continue to go undetected or not. But I'll leave that up to whether to value your Hi-Rez account or not.
> 
> If you want to see what the log file should look like, here are three examples from my own play session from randomly chosen games (with some information redacted), playing natively on a bare-metal Windows 10 machine. Notice how all of them have no mention, or reference of an error? This is what it should look like when you launch one of these games, any mention of an error in the `loader.log`, and it most likely isn't working as the developers intended.
> 
> EDIT: GitHub also destroyed my log upload. https://privatebin.net/?d00326c27e80bfc6#4WdUt8CZkLxBQ3WTpBQKYbU4V4ir8QKtXATrUduBhnx6 https://privatebin.net/?f62472207f52e14e#8mTtsK4eNKpNLcopLguguUYD7dVuLoBKWHhssaUF2ew7 https://privatebin.net/?e68156e0ef6a3710#AngkRYunPQmp8sHadm4EUCqDou85uYA5qBuFQ3LgKagg

My loader.log is different, I don't have the 0% thing

loader.log https://pastebin.com/Gi4MBWM5
gamelauncher.log https://pastebin.com/uEiVUMk6

**Comment by Rafii2198** [comment]
It can be false alarm but someone on ProtonDB just played the game using Proton-GE as it crashed on normal Proton for him and he said it run flawlessly. It is 4am and I can't check it now so if someone can check it for us, I will be grateful.

Especially as Smite is listed as Supported and it is made by the same company.

**Comment by akatsukilevi** [comment]
Would need to check the log files to be able to determine if EAC works or not
