### ISSUE TITLE
Data sources?

### ISSUE THREAD

**Issue by dpanter** [Starz0r/AreWeAntiCheatYet#15]
Please define "trustworthy and reliable source" in the readme, and clarify what the sources are for your data.
What counts as a confirmed working title?
Is this project meant for Proton, Wine, Native titles?

**Comment by MathiewMay** [comment]
> It is simply intended to show which games work on Linux,


Anti-Cheat's for games

**Comment by Curve** [comment]
I would define a trustworthy and reliable source as a source where one or multiple of the following conditions are met:

- Someone that is part of development team or studio of the game has confirmed something in regard to the Anti-Cheat
    - It is required that you can verify for yourself that the person quoted from this source is who he claims to be
- Multiple people that all describe the same symptoms of the anti-cheat working (i.e. a ProtonDB listing, where recent reports all seem to indicate that the game is working)
    - Preferably includes the required steps to reproduce the described behavior
    - There are game logs that suggest the game is doing something specific when it detects Linux (i.e. PSO2 explicitly allows Linux currently)
- A link to the game which works out of the box (can also be a ProtonDB listing)

A note to the ProtonDB Listings:  
It would be greatly preferred when there are indications that suggest that the game explicitly changed something regarding their anti-cheat - e.g. addition of the required EAC files for linux (if applicable please also provide a steamdb link then as well as a protondb listing which shows that the game does indeed function after said changes have been done)

**Comment by Curve** [comment]
> Is this project meant for Proton, Wine, Native titles?

All of the them.

> What counts as a confirmed working title?

You can read up on the definitions on the website by expanding "Legend"
