### ISSUE TITLE
Sector's Edge

### ISSUE THREAD

**Issue by BunnyBotDev** [Starz0r/AreWeAntiCheatYet#150]
### Game Title

Sector's Edge

### Game Website

https://store.steampowered.com/app/1024890/Sectors_Edge/#:~:text=Sector's%20Edge%20is%20an%20indie,destruction%20of%20Ace%20of%20Spades.

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention

N/A

**Comment by Starz0r** [comment]
Added in https://github.com/Starz0r/AreWeAntiCheatYet/commit/93f77dd5fd968cfa32b2a23f3300238167540e23
