### ISSUE TITLE
Elite Dangerous

### ISSUE THREAD

**Issue by BunnyBotDev** [Starz0r/AreWeAntiCheatYet#151]
### Game Title

Elite Dangerous

### Game Website

https://www.elitedangerous.com/

### Anti-Cheat Software

Other

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention

N/A

**Comment by Starz0r** [comment]
Does this game even have anti-cheat? From what I gather, it does not look like it.

Can anyone else confirm?
