### ISSUE TITLE
Another list

### ISSUE THREAD

**Issue by BuyMyMojo** [Starz0r/AreWeAntiCheatYet#154]
Just sharing in case it's useful
https://aclist.github.io/

**Comment by Starz0r** [comment]
Thanks for sharing! I saw this originally when you had submitted, but didn't have much to say about it. I don't mind having multiple sites, managed by different users, dedicated to the same purpose, but at the time I didn't know how I'd feel about it, or in the future. Right now, it seems that we are ahead of the list by a lot, and when I was starting out I had used this list even as a reference. It seems to have drifted out of sync, but I will keep it in my mind if that ever changes.
