### ISSUE TITLE
<Game Name Here>Rogue Company

### ISSUE THREAD

**Issue by JEZZADJ** [Starz0r/AreWeAntiCheatYet#156]
### Game Title

Rogue Company 

### Game Website

https://www.roguecompany.com/

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

🎉 Confirmed

### Proof of Mention

n/a

**Comment by Starz0r** [comment]
Thank you for the submission.

You left `Proof of Mention` empty. Where did you get the information that Rogue Company was confirmed getting anti-cheat compatibility support?

**Comment by JEZZADJ** [comment]
I tried it on pc and it ran perfectly. Sent from Mail for Windows From: Starz0rSent: 13 October 2021 20:21To: Starz0r/AreWeAntiCheatYetCc: JEZZADJ; AuthorSubject: Re: [Starz0r/AreWeAntiCheatYet] <Game Name Here>Rogue Company (#156) Thank you for the submission.You left Proof of Mention empty. Where did you get the information that Rogue Company was confirmed getting anti-cheat compatibility support?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Starz0r** [comment]
Can you post your `loader.log` file so we can verify this?

**Comment by kieeps** [comment]
just a FYI, i can not get it to work. i'd LOVE if this game worked but i get EAC errors at startup

**Comment by Starz0r** [comment]
Thirty days have passed, and I could not get a proper confirmation on this.

Feel free to resubmit or reopen if you have actual information regarding the game.
