### ISSUE TITLE
Add Brawlhalla (tech-test Steam beta) to supported 

### ISSUE THREAD

**Issue by Saladin1812** [Starz0r/AreWeAntiCheatYet#164]
### Game Title

Brawlhalla

### Game Website

https://www.brawlhalla.com/

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

⭐ Supported

### Proof of Mention

https://www.gamingonlinux.com/2021/10/brawlhalla-to-get-easy-anti-cheat-dev-puts-up-beta-with-eac-working-on-linux-with-proton

**Comment by jatin-cbs** [comment]
Sorry its a duplicate
