### ISSUE TITLE
League Of Legends

### ISSUE THREAD

**Issue by HenkoHallows** [Starz0r/AreWeAntiCheatYet#166]
### Game Title

League Of Legends

### Game Website

Leagueoflegends.com

### Anti-Cheat Software

Other

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention

Leagueoflegends.com

**Comment by puyoxyz** [comment]
status should be supported, see [r/LeagueOfLinux](https://reddit.com/r/LeagueOfLinux)

**Comment by rurigk** [comment]
I play league of legends in linux, its supported in wine but you need to patch things (see lutris installers)

Is know that Riot Games wants to add anticheat software for league of legends but we don't know if is going to work with wine in the future (probably not)

Currently far as i know league of legends does not have any anticheat
