### ISSUE TITLE
Back 4 Blood

### ISSUE THREAD

**Issue by MathiewMay** [Starz0r/AreWeAntiCheatYet#17]
### Game Title

Back 4 Blood

### Game Website

https://www.back4blood.com/

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention

N/A

**Comment by BulletBlaster** [comment]
The Beta version works on Linux: [https://www.gamingonlinux.com/2021/08/looks-like-the-fresh-back-4-blood-beta-is-working-on-linux-with-proton-ge](https://www.gamingonlinux.com/2021/08/looks-like-the-fresh-back-4-blood-beta-is-working-on-linux-with-proton-ge)
