### ISSUE TITLE
Update Smite

### ISSUE THREAD

**Issue by pupilo-py** [Starz0r/AreWeAntiCheatYet#178]
### Game Title

Smite

### Status of the Anti-Cheat

⭐ Supported

### Proof of Mention

YES

**Comment by MathiewMay** [comment]
Please look at #14 yes the game works with the anti cheat but it is not officially supported as the anti cheat never loads correctly.

**Comment by maklamj** [comment]
**NO**, EAC is not working properly.
https://www.reddit.com/r/linux_gaming/comments/q7cgcx/comment/hghl7dh/

**Comment by Starz0r** [comment]
It's been 30 days without an update on this, so I'm going to go ahead and close these. If Hi-Rez decides to move forward with real support, and I don't notice, feel free to reopen this.
