### ISSUE TITLE
Update Bless Unleashed

### ISSUE THREAD

**Issue by pupilo-py** [Starz0r/AreWeAntiCheatYet#179]
### Game Title

Bless Unleashed

### Status of the Anti-Cheat

⭐ Supported

### Proof of Mention

YES

**Comment by pupilo-py** [comment]
unfortunately, I looked here and couldn't find it, but he posted the video, he must have deleted it or something.

**Comment by PedroSilva8** [comment]
I tested the game right now and it's not working, it kicks you after a few minutes saying there is an authentication issue and checking the EAC log file confirms that it is not working correctly

**Comment by Starz0r** [comment]
It's been 30 days without an update on this, so I'm going to go ahead and close these. If Round8 or Neowiz decides to move forward with real support, and I don't notice, feel free to reopen this.
