### ISSUE TITLE
Supported Status

### ISSUE THREAD

**Issue by MathiewMay** [Starz0r/AreWeAntiCheatYet#180]
Can we all agree that games should only be set as supported if the anti-cheat was officially implemented to work with Linux by the game's developers? 

Some games might work on Linux with their anti-cheat yet they are not officially implemented in that case they should remain unsupported.

Some example are #14 and #166

**Comment by Starz0r** [comment]
I've sorta peeled back on this slightly with the redesign, with regard to allowing two different statuses to refer to the game being playable on the platform. However, this does not completely absolve developer responsibility as it still requires developers to allow their game to be playable, while not patching it out, lest they get put in the `Denied` or `Broken` category.

Closing this as solved. If there are any further questions, feel free to reopen.
