### ISSUE TITLE
Honkai Impact 3rd

### ISSUE THREAD

**Issue by codiecher** [Starz0r/AreWeAntiCheatYet#209]
### Game Title

Honkai Impact 3rd

### Game Website

https://honkaiimpact3.mihoyo.com/asia/en-us/home

### Anti-Cheat Software

Other

### Status of the Anti-Cheat

🚫 Denied

### Proof of Mention

N/A

**Comment by romulasry** [comment]
Does not work on Proton Experimental as of today, see: [#5241](https://github.com/ValveSoftware/Proton/issues/5241)
