### ISSUE TITLE
Squad

### ISSUE THREAD

**Issue by abienz** [Starz0r/AreWeAntiCheatYet#21]
### Game Title

Squad

### Game Website

https://joinsquad.com/

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

⭐ Enabled

### Proof of Mention

n/a

**Comment by Starz0r** [comment]
I actually did add this in https://github.com/Starz0r/AreWeAntiCheatYet/commit/fb14ac80259dd2b6aef83680a96a9221af024a73 when I woke up, just forgot to close this when I did include it.

Thank you for the submission!

**Comment by Starz0r** [comment]
@Newbytee Could you link where a workaround is needed? I'll change the status on the site if you can provide this.

**Comment by Newbytee** [comment]
See https://www.protondb.com/app/393380
