### ISSUE TITLE
[SECURITY] Package 'coa' has been hijacked and currently should not be updated

### ISSUE THREAD

**Issue by seeeeew** [Starz0r/AreWeAntiCheatYet#224]
The package 'coa' has been hijacked and is apparently stealing passwords in new versions. The last official and safe version is 2.0.2, which is currently in use in this project. Make sure you don't accidentally update it before this matter is resolved.

https://www.bleepingcomputer.com/news/security/popular-coa-npm-library-hijacked-to-steal-user-passwords/

**Comment by Curve** [comment]
Package is no longer used since #456
