### ISSUE TITLE
Lost Ark

### ISSUE THREAD

**Issue by nicobatty** [Starz0r/AreWeAntiCheatYet#225]
### Game Title

Lost Ark

### Game Website

https://www.playlostark.com/

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention

N/A

**Comment by Galcian79** [comment]
Well i think this game should be listed as denied too.
![IMG_20220419_190623](https://user-images.githubusercontent.com/38818634/164057982-66550708-ff90-4486-8acc-f437ccf2b8c8.jpg)
