### ISSUE TITLE
Update Mount & Blade II: Bannerlord

### ISSUE THREAD

**Issue by Nathan-Mossaad** [Starz0r/AreWeAntiCheatYet#227]
### Game Title

Mount & Blade II: Bannerlord

### Status of the Anti-Cheat

⭐ Supported

### Proof of Mention

https://store.steampowered.com/news/group/4145017/view/3104663180636096966

**Comment by Nathan-Mossaad** [comment]
I sadly can't verify this, as I don't have the game.

**Comment by daoert** [comment]
Got kicked from the match with Proton Experimental and Steam Client Beta.

**Comment by doogie544** [comment]
> Got kicked from the match with Proton Experimental and Steam Client Beta.

You might try again. There appears to have been an error in steam.  A new tool should have been downloaded called "Proton Battleye Runtime".  While I am not clear what happened, either it was not added to the steam beta as it should have been (this is what I think happened according to the report about it I read on the protondb discord) or it was not automatically being downloaded by steam.

I would try again not that it was fixed- the fix came after your comment here I believe.  If is still does not work, try searching for the Proton battleye runtime in your steam library by name and see if it is installed and if not try manually installing it and then trying the game again.

I can find it by name when searching even tho I am not using the steam beta, but have not tried manually installing it for obvious reasons
