### ISSUE TITLE
Super Animal Royale

### ISSUE THREAD

**Issue by ghost** [Starz0r/AreWeAntiCheatYet#231]
### Game Title

Super Animal Royale

### Game Website

https://animalroyale.com

### Anti-Cheat Software

Other

### Status of the Anti-Cheat

⭐ Supported

### Proof of Mention

https://www.protondb.com/app/843380

**Comment by againstalllog1c** [comment]
Notable for being the only active and playable battle royale game on Linux currently, unless you count BFV Firestorm or CSGO Danger Zone. Creative Destruction, a mobile game ported to Steam, also works..but it's so bad it isn't worth mentioning

**Comment by Faalagorn** [comment]
> Notable for being the only active and playable battle royale game on Linux currently, unless you count BFV Firestorm or CSGO Danger Zone. Creative Destruction, a mobile game ported to Steam, also works..but it's so bad it isn't worth mentioning

There's a surviv.io, but only through browser.
