### ISSUE TITLE
Update Rainbow Six Siege

### ISSUE THREAD

**Issue by MrNessuno** [Starz0r/AreWeAntiCheatYet#234]
### Game Title

Rainbow Six Siege

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention

https://store.steampowered.com/news/group/4145017/view/3104663180636096966 
https://www.reddit.com/r/linux_gaming/comments/qo5e0b/rainbow_6_siege_working_on_linux_with_proton/

### What happen
The game launch and don't give any BattlEye error. Multiplayer is playable.
Launched via Steam Beta with Proton Experimental + Proton Battleye Runtime

**Comment by MrNessuno** [comment]
Is there a way to see if BattlEye is working correctly? We can't find how to see BattlEye's log files

**Comment by MathiewMay** [comment]
The first link does not mention anything about r6 and the 2nd one does not show any kind of log that the anti cheat loaded correctly, also your proton logs does not mean anything any game that has the BattleEye anti-cheat will load the BattleEye dll.

**Comment by MrNessuno** [comment]
> The first link does not mention anything about r6 and the 2nd one does not show any kind of log that the anti cheat loaded correctly, also your proton logs does not mean anything any game that has the BattleEye anti-cheat will load the BattleEye dll.

ye, i'm asking how to log Battleye to check if is working or not. I can't find anything about this online.

**Comment by MathiewMay** [comment]
> > The first link does not mention anything about r6 and the 2nd one does not show any kind of log that the anti cheat loaded correctly, also your proton logs does not mean anything any game that has the BattleEye anti-cheat will load the BattleEye dll.
> 
> ye, i'm asking how to log Battleye to check if is working or not. I can't find anything about this online.

I am not sure but if this is a bad implementation of the anti-cheat which would be unlikely for a massive game like this but still, you could get banned because of how r6 handles banning (in waves) i would not recommend actually playing the game as you could get flagged.

**Comment by MrNessuno** [comment]
> > > The first link does not mention anything about r6 and the 2nd one does not show any kind of log that the anti cheat loaded correctly, also your proton logs does not mean anything any game that has the BattleEye anti-cheat will load the BattleEye dll.
> > 
> > 
> > ye, i'm asking how to log Battleye to check if is working or not. I can't find anything about this online.
> 
> I am not sure but if this is a bad implementation of the anti-cheat which would be unlikely for a massive game like this but still, you could get banned because of how r6 handles banning (in waves) i would not recommend actually playing the game as you could get flagged.

That's true, I just did one match online to be sure it's working and trying to get some logs and I closed the game after it. I just want to find a way to confirm all is working fine or not.

**Comment by MathiewMay** [comment]
Confirmed not implemented. No longer working. Just try for your self you will get kicked. No bans doe.
