### ISSUE TITLE
Update Genshin Impact

### ISSUE THREAD

**Issue by MrNessuno** [Starz0r/AreWeAntiCheatYet#236]
### Game Title

Genshin Impact

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention

[REDACTED]

**Comment by MrNessuno** [comment]
I'm playing since version 2.0 with this patch with no problems.

**Comment by Starz0r** [comment]
This is literally straight up just a bypass for the anti-cheat on Linux. It even says not to share it publically on the repo you linked.
