### ISSUE TITLE
Nostale 

### ISSUE THREAD

**Issue by hydrasho** [Starz0r/AreWeAntiCheatYet#246]
Why nostale is unsuported?
I have always been able to play nostale since always even since 4.0, I tried again today I am level 85😅 it is even gold on protondb because of a bug in proton6 but it works!

**Comment by maklamj** [comment]
"Unconfirmed" but why the hell is it described that way?
It works 100% fine although newer versions of Wine have reintroduced an old bug, older versions work fine (same with Proton).

**Comment by hydrasho** [comment]
this is surely an error but even the proton 6 bug has nothing to do with an anti cheat anyone

**Comment by maklamj** [comment]
Yup.
Also why they assigned "nProtect GameGuard" to it.. I don't think there is any official post confirming this, no source on AWACY either.

**Comment by hydrasho** [comment]
I even think that nostale does not have anti cheat

**Comment by PSzczepanski1996** [comment]
And bam, it's supported now and the issue was not Anti-Cheat but some really wonky anti-bug protection for pointers:
https://github.com/PSzczepanski1996/proton-ge-nostale
