### ISSUE TITLE
Update <Game Name Here>

### ISSUE THREAD

**Issue by Scorpion8754** [Starz0r/AreWeAntiCheatYet#251]
### Game Title

Planetside 2

### Status of the Anti-Cheat

⭐ Supported

### Proof of Mention

https://old.reddit.com/r/Planetside/comments/qrl1hq/guide_running_planetside_2_on_linux/

**Comment by Starz0r** [comment]
It'd be nice if we could get a developer's statement on this before I mark it as officially supported.
