### ISSUE TITLE
Planetside 2 Anticheat Is working

### ISSUE THREAD

**Issue by Jpnyman** [Starz0r/AreWeAntiCheatYet#252]
### Game Title

Planetside 2

### Status of the Anti-Cheat

⭐ Supported

### Proof of Mention

N/A

**Comment by PedroSilva8** [comment]
Can confirm
![Screenshot_20211128_175225](https://user-images.githubusercontent.com/24511224/143779814-22a6e908-581f-41ac-8313-86ccbf393dbe.png)

**Comment by Starz0r** [comment]
I'm still somewhat hesitant, ProtonDB seems fairly forthcoming that everything is fine, but I have yet to see an official response from a developer.

Did they just make this change without informing their users? Or is there a chance that the new runtime fixes the issues and that players are just at risk of being kicked and banned at any moment?

**Comment by Atemu** [comment]
> Did they just make this change without informing their users? Or is there a chance that the new runtime fixes the issues and that players are just at risk of being kicked and banned at any moment?

From what we know, the latter. Planetside 2 doesn't seem to be the only game like this though, so perhaps there is something more to it?

Might warrant a new category.

**Comment by PedroSilva8** [comment]
Maybe there should be a status called "Working/Unconfirmed" or something like that?
But if you add that there should be a 1-2 week delay before adding to avoid false positives like smite that allow people to play for a few days to then be blocked again
