### ISSUE TITLE
Dayz

### ISSUE THREAD

**Issue by Alucard174** [Starz0r/AreWeAntiCheatYet#266]
### Game Title

BOHEMIA INTERACTIVE®

### Game Website

https://dayz.com/

### Anti-Cheat Software

BattlEye

### Status of the Anti-Cheat

⭐ Supported

### Proof of Mention

N/A

**Comment by AuthFailed** [comment]
Hi! Thank you for the information. Maybe you found a way to run the game with mods?

**Comment by Alucard174** [comment]
But with mods, we haven't found a way yet... dayzsa doesn't start either... I think it's possible to run through cmd or bat files somehow, but nothing comes out yet.... But here, most likely, I'm doing something wrong.... I wonder how to run it with mods

**Comment by bastimeyer** [comment]
I've just created a CLI launcher for DayZ which lets you set up mods and lets you connect to servers automatically:
https://github.com/bastimeyer/dayz-linux-cli-launcher

Additional Reddit thread here:
https://www.reddit.com/r/linux_gaming/comments/r9zz6n/ive_created_a_launcher_for_dayz_on_linux_which/
