### ISSUE TITLE
Zero Hour

### ISSUE THREAD

**Issue by intruden313** [Starz0r/AreWeAntiCheatYet#27]
### Game Title

Zero Hour

### Game Website

https://store.steampowered.com/app/1359090/Zero_Hour/

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention

n/a

**Comment by Curve** [comment]
Where does "AntiCheat: EasyAntiCheat" come from? Is there any proof for this claim?

All I could find was that they want to add Denuvo Anti-cheat but have not done yet and will announce it shortly https://store.steampowered.com/news/app/1359090/view/3191371430398762496
