### ISSUE TITLE
Century: Age of Ashes

### ISSUE THREAD

**Issue by flashrocket** [Starz0r/AreWeAntiCheatYet#277]
### Game Title

Century: Age of Ashes

### Game Website

https://www.century-age-of-ashes.com/

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention

N/A

**Comment by flashrocket** [comment]
Steam Link: [https://store.steampowered.com/app/918570/Century_Age_of_Ashes/](https://store.steampowered.com/app/918570/Century_Age_of_Ashes/)

**Comment by iSaluki** [comment]
Game is supported, see #280

**Comment by flashrocket** [comment]
Closing duplicate issue.
