### ISSUE TITLE
Century: Age of Ashes

### ISSUE THREAD

**Issue by iSaluki** [Starz0r/AreWeAntiCheatYet#280]
### Game Title

Century: Age of Ashes

### Game Website

https://store.steampowered.com/app/918570/Century_Age_of_Ashes/

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

⭐ Supported

### Proof of Mention

Game released on Dec 2, with Proton support enabled from day 1

**Comment by rjousse18** [comment]
It works for now but it's not really supported, EAC should not be enabled, once the game will activate EAC, it probably won't work

**Comment by iSaluki** [comment]
See these messages:

https://discord.com/channels/782325777408065597/785812083165102091/918161386608140309

https://discord.com/channels/782325777408065597/785812083165102091/918162375880896524

To view those messages, you need to join the Century Discord server. 

This suggests that EAC support is intentional.

**Comment by rjousse18** [comment]
https://www.reddit.com/r/linux_gaming/comments/q0g9rl/comment/hf7z4y6/?utm_source=share&utm_medium=web2x&context=3

I have no file easyanticheat or loader.log on my wine files. When the game launch, easy anti cheat appears then disappears whithout loading bar so -> they did not activate proton support. EAC is just not enabled at all. Sometimes the problems also occurs on Paladins when they update the game.

**Comment by flashrocket** [comment]
@iSaluki from discord It seems the devs are aware of gameplay on proton though. But until we get official confirmation I don't think marking this as Supported is good. Also do we have any log files to confirm loading of anti cheat?

**Comment by iSaluki** [comment]
Yeah, it would be worth waiting a while.


I will look into checking if EAC actually starts a bit later and will post what I find here.

**Comment by iSaluki** [comment]
I've just run a few tests, and this is what I've found:

- Easy Anti Cheat is required for the game to start, if the files are removed it will refuse to start.
- None of the game logs mention EAC, Easy Anti Cheat, or any kind of anticheat, so I cannot confirm if it is started that way.
- The localisation files include error messages for Easy Anti Cheat not being initialised, which I can trigger. However, if I don't mess with the local files it all works fine.

This suggests that the game has enabled EAC support for Proton, however I am not an expert and this isn't conclusive.

**Comment by gardotd426** [comment]
>The localisation files include error messages for Easy Anti Cheat not being initialised, which I can trigger. However, if I don't mess with the local files it all works fine.

That seems to indicate that it's not enabled. 

The discord messages also indicate that it's not enabled, just that they aren't stopping it from working (yet).

**Comment by Curve** [comment]
Regarding the recent protondb reports I will add this game as broken.
