### ISSUE TITLE
Update Insurgency: Sandstorm

### ISSUE THREAD

**Issue by B0TJerry** [Starz0r/AreWeAntiCheatYet#288]
### Game Title

Insurgency: Sandstorm

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention

https://newworldinteractive.com/update-1-11-operation-warlord-steam-hotfix-4/

**Comment by Curve** [comment]
[Game still seems to work](https://www.protondb.com/app/581320) and your reference link is dead
