### ISSUE TITLE
Grand Theft Auto Online

### ISSUE THREAD

**Issue by itsnoa04** [Starz0r/AreWeAntiCheatYet#292]
### Game Title

Grand Theft Auto Online

### Game Website

https://www.rockstargames.com/GTAOnline/

### Anti-Cheat Software

Other

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention

N/A

**Comment by Jacksaur** [comment]
> its only to archive kernel anti cheat software. gtao doessn have one

VAC isn't kernel level. This is anticheat in general.

**Comment by Faalagorn** [comment]
Doesn't GTA V work for Online on Proton though?

**Comment by Curve** [comment]
> Doesn't GTA V work for Online on Proton though?

It does
