### ISSUE TITLE
DRAGON BALL XENOVERSE

### ISSUE THREAD

**Issue by Alucardac1** [Starz0r/AreWeAntiCheatYet#296]
### Game Title

DRAGON BALL XENOVERSE

### Game Website

https://en.bandainamcoent.eu/dragon-ball/dragon-ball-xenoverse

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention

N/A

**Comment by Ultraguy24** [comment]
Sorry to reopening this change, this appears to have added DRAGON BALL Xenoverse 2 instead of DRAGON BALL Xenoverse, both are seperate games and both do not work
