### ISSUE TITLE
Request: Ready or Not

### ISSUE THREAD

**Issue by JoneKone** [Starz0r/AreWeAntiCheatYet#305]
### Game Title

Ready or Not

### Game Website

https://voidinteractive.net/

### Anti-Cheat Software

Other
(We will be utilizing a well respected and high quality anti-cheat system, but cannot name them yet as we are still in negotiation.)

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention
Edit. added a picture
![Screenshot from 2022-06-10 15-02-16](https://user-images.githubusercontent.com/1114115/173060467-718b5396-b2a3-4701-afb7-bd849658a569.png)

**Comment by Curve** [comment]
The game doesn't have any anti-cheat yet which is why I'm hesitant to list it - As soon as it adds any anti-cheat I'll add it ^^

**Comment by Starz0r** [comment]
I'm also willing to keep this open as a reminder for maybe a year? It should come sooner than that, but if not, I will close it.

**Comment by JoneKone** [comment]
> The game doesn't have any anti-cheat yet which is why I'm hesitant to list it - As soon as it adds any anti-cheat I'll add it ^^

They have said they will put anti-cheat on it. Soon tm. The issue in my mind is, that ppl buy it now thinking it will work.. and.. when they slap anti cheat on it.. and say noppers.. I don't think they are in any obligation to return the money.

**Comment by Curve** [comment]
> > The game doesn't have any anti-cheat yet which is why I'm hesitant to list it - As soon as it adds any anti-cheat I'll add it ^^
> 
> They have said they will put anti-cheat on it. Soon tm. The issue in my mind is, that ppl buy it now thinking it will work.. and.. when they slap anti cheat on it.. and say noppers.. I don't think they are in any obligation to return the money.

If you buy it on steam you can make use of their return policy which is pretty good

**Comment by maplepy** [comment]
> > > The game doesn't have any anti-cheat yet which is why I'm hesitant to list it - As soon as it adds any anti-cheat I'll add it ^^
> > 
> > 
> > They have said they will put anti-cheat on it. Soon tm. The issue in my mind is, that ppl buy it now thinking it will work.. and.. when they slap anti cheat on it.. and say noppers.. I don't think they are in any obligation to return the money.
> 
> If you buy it on steam you can make use of their return policy which is pretty good

It's it within 14 days and you played less than 2 hours yes

**Comment by Curve** [comment]
> 

Yeah and when the Anti-Cheat doesn't work you can easily return it.

However I don't see why the game should be listed then - as it doesn't have Anti-Cheat yet

**Comment by maplepy** [comment]
But if you had it for some time you can't return it can you?

**Comment by Curve** [comment]
> But if you had it for some time you can't return it can you?

Well if you bought it before checking if it plans to support Linux and then keep it for 2 weeks or play longer than 2 hours - No you can't return it but I'd argue it would be logical to check that before you buy the game on Linux

**Comment by maplepy** [comment]
So I'm not sure why you said that 

> > > The game doesn't have any anti-cheat yet which is why I'm hesitant to list it - As soon as it adds any anti-cheat I'll add it ^^
> > 
> > 
> > They have said they will put anti-cheat on it. Soon tm. The issue in my mind is, that ppl buy it now thinking it will work.. and.. when they slap anti cheat on it.. and say noppers.. I don't think they are in any obligation to return the money.
> 
> If you buy it on steam you can make use of their return policy which is pretty good

**Comment by Curve** [comment]
> So I'm not sure why you said that 
> 
> > > > The game doesn't have any anti-cheat yet which is why I'm hesitant to list it - As soon as it adds any anti-cheat I'll add it ^^
> > > 
> > > 
> > > They have said they will put anti-cheat on it. Soon tm. The issue in my mind is, that ppl buy it now thinking it will work.. and.. when they slap anti cheat on it.. and say noppers.. I don't think they are in any obligation to return the money.
> > 
> > If you buy it on steam you can make use of their return policy which is pretty good
> 
> 

The game states that it will add anticheat, what I'm saying is, due to the game stating it will add anticheat you should be careful when buying it now - When you buy it at a later date when it already has the Anti-Cheat you can buy it to check if it works and if it doesn't return it.

**Comment by Curve** [comment]
The FAQ entry has changed changed by now - I'm not sure when to expect any progress from them.

Please re-open this issue or make a new one when the status updates.
