### ISSUE TITLE
<God of War>

### ISSUE THREAD

**Issue by Neddie67** [Starz0r/AreWeAntiCheatYet#310]
### Game Title

God of War

### Game Website

https://store.steampowered.com/app/1593500/God_of_War/

### Anti-Cheat Software

VAC

### Status of the Anti-Cheat

⭐ Supported

### Proof of Mention

N/A

**Comment by braiam** [comment]
Can someone confirm that it actually uses it? GoW doesn't have any multiplayer capabilities, so it is weird.

**Comment by Starz0r** [comment]
If it happens that God of War does indeed have anti-cheat for whatever reason, please re-open this. At the moment this does not seem to be the case, so I will close this for now.
