### ISSUE TITLE
Update STAR WARS™: Squadrons

### ISSUE THREAD

**Issue by lolsniperftw** [Starz0r/AreWeAntiCheatYet#315]
### Game Title

STAR WARS™: Squadrons

### Status of the Anti-Cheat

🎉 Confirmed

### Proof of Mention

https://steamdb.info/app/1222730/depots/?branch=eac_fix

**Comment by Starz0r** [comment]
Fixed in https://github.com/Starz0r/AreWeAntiCheatYet/commit/8f56d5aeea55247e926f6d145addbc92101e7f2a

**Comment by lolsniperftw** [comment]
Uhmmmm I don't see it fixed in https://github.com/Starz0r/AreWeAntiCheatYet/commit/8f56d5aeea55247e926f6d145addbc92101e7f2a

**Comment by Starz0r** [comment]
@lolsniperftw Apologies, it must have not saved when I changed it the first time. It should be changed now.
