### ISSUE TITLE
SMITE

### ISSUE THREAD

**Issue by JEZZADJ** [Starz0r/AreWeAntiCheatYet#316]
### Game Title

SMITE

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

⭐ Supported

### Proof of Mention

https://steamdb.info/depot/386361/history/

**Comment by Starz0r** [comment]
Fixed in https://github.com/Starz0r/AreWeAntiCheatYet/commit/8f56d5aeea55247e926f6d145addbc92101e7f2a

**Comment by doogie544** [comment]
I think it may have been a bit premature to mark the game as supported.

Yes the files in the link were added to the game, however it does not appear that EAC is actually running properly.

The logs are exactly the same as they were before and there is no proton compatible  EAC  module in the prefix as there would be if everything was working properly.

Below is the *entire*  loader.log

```
[2022.02.03-20.05.15] Loader initialized.
[2022.02.03-20.05.15] [EAC Callback] Code 914. Message: ''.
```

This is the *entire*  gamelauncher.log a bit longer but still not showing much

```
[Info] Desktop screen settings detected. DPI: 96 DPI Multiplier: 1.000000 BPP: 32.
[Info] Localization loaded for: 'en-US'.
[Info] Settings file path: 'EasyAntiCheat/Launcher/Settings.json'.
[Info] Start. ExecutablePath: 'Win32\Smite.exe' LaunchParameters: '-pid=017 -steam -anon  -seekfreeloadingpcconsole -eac_dir ..\\EasyAntiCheat\\' WorkingDirectory: ''.
[Info] [LauncherFinished] EACAsyncResult: 0 Message: 'Easy Anti-Cheat successfully loaded in-game'.
[Info] Finished window initialization.
[Info] Unloading the EasyAntiCheat library.
[Info] Destroying windows.
[Info] Exit.
```

That does not look to me like EAC is properly being downloaded and running and as I already state, there is no proton EAC module in the prefix and that is exactly what the logs looked like months ago when EAC was known to no be working

My guess is that Hi-Rez is considering adding proton support as they have added the files to the game however by all appearances it does not look like they have turned that compatibility on despite added the needed files to the game, quite possibly they are testing it internally but I would suspect that when or if EAC support is turned there will be some kind of announcement.

It would appear that just a link showing that files were added to the steamdb is not sufficient enough proof that EAC is supported.

(just as an aside this site still shows smite as unsupported:  https://aclist.github.io/  )
