### ISSUE TITLE
Dark Messiah of Might and Magic

### ISSUE THREAD

**Issue by dimetime** [Starz0r/AreWeAntiCheatYet#320]
### Game Title

Dark Messiah of Might and Magic

### Game Website

https://store.steampowered.com/app/2100/Dark_Messiah_of_Might__Magic/

### Anti-Cheat Software

Other

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention

N/A

**Comment by Curve** [comment]
The game is singe-player only as far as I'm aware and I couldn't find any information suggesting the game uses any sort of anticheat
