### ISSUE TITLE
Update Hell Let Loose

### ISSUE THREAD

**Issue by BrenniusXIV** [Starz0r/AreWeAntiCheatYet#321]
### Game Title

Hell Let Loose

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention

N/A

**Comment by BrenniusXIV** [comment]
Developers have yet to make a statement regarding whether Proton support for EAC is actually occurring. Discord moderators pinned information regarding the current up-to-date method for the devs to upgrade.

It appears that ```bin/games.txt ``` correctly reflects this situation, but ```src/static/games.json``` incorrectly states that developers have confirmed Proton support for the title.

**Comment by Starz0r** [comment]
It seems they did at one point have the native libraries and/or a SteamDeck testing branch that is now deleted. I will mark this change in `games.txt` and https://github.com/Starz0r/AreWeAntiCheatYet/issues/327.
