### ISSUE TITLE
Update Fall Guys: Ultimate Knockout

### ISSUE THREAD

**Issue by Cryotize** [Starz0r/AreWeAntiCheatYet#322]
Currently, the Website says "Confirmed". When clicking on it, you'll get redirected to https://www.theverge.com/2021/10/5/22709918/valve-steam-deck-supported-games-anti-cheat-proton-eac-battleye-epic 

There is no confirmation on EAC Support for Fall Guys whatsoever. Please set it to "Unconfirmed" or update the source.

**Comment by TheBlueOompaLoompa** [comment]
#326

**Comment by Starz0r** [comment]
Explained in more detail in https://github.com/Starz0r/AreWeAntiCheatYet/issues/327.
