### ISSUE TITLE
Ability to check new changes

### ISSUE THREAD

**Issue by Rafii2198** [Starz0r/AreWeAntiCheatYet#337]
So I like to follow the growth of Linux support, my small issue is that it actually grew so much already that it is kinda hard to track, before I just remembered most games and their state but it is changing so fast (which is fascinating) that it's hard to keep track of.

My suggestion is to add maybe a button or something to only show changed/added games since past 7 days or something like that, this would give a good overview of what happened since last week without overwhelming amount of information.

This is mostly for those like me who like to analyze changes. It would also show the growth of Linux anti cheat support and the page itself.

**Comment by Starz0r** [comment]
I totally agree that the interface can use some slimming down, and a way to quickly analyze recent changes. Though, I'm not sure how it'd be presented on the front-end while still keeping everything clean and concise. Open to suggestions.

**Comment by Rafii2198** [comment]
Thinking about it, how about changing Show Breakdown button to Filter button when you would be able to filter games by, I dunno, Anti cheat it uses, status, it could also has this idea of recent changes, maybe also if it is on Steam, EGS, Origin, etc.
I think it would benefit even more people than the original idea, people having to look at over 200 just to check out about the status may not be that good, if that would be narrowed down, to for example check what games on uPlay are supported, then it would be more accessible for everyone.

And then I would move the Show Breakdown button to the right of the progress bar, and change it to be just arrow down to not take up space, than after clicked it would roll out current breakdown.

**Comment by Rafii2198** [comment]
I made a super quick mocap, and I mean really quick, just to get the idea, I don't imagine it to look like this exactly cos, well its ugly, but this is just to get the idea
![obraz](https://user-images.githubusercontent.com/26695327/154503078-2dd97e78-4731-4bf2-9e0f-064b7e64d5c2.png)

**Comment by Rafii2198** [comment]
Another small update, no image this time.
Apart from making it look in style of the page I think these points should be considered while designing filtering menu:
- All check boxes should use smaller solid color box as means to show it's selected, if radio then same but with circle instead
- Sections should be separated subtly, the lines I made are on the border of "subtly", nothing more distinct
- Any icons used there should be exactly the same size as text and squared (although I think all these logos are squares already anyway)
- Size of filtering menu should be limited, user cannot be overflown with informations all at once. I imagine that each section could be scrollable independently for more free navigation
- If it's possible then it would be very nice if information means (these capsules at the top and progress bars below it) updated dynamically according to the filtering. Progress bars should have little, at most 1.25 second long animation.

*(These are just my points, you don't have to listen to me obviously 😜)*

Maybe if I get enough free time then I'll try design it more in-depth.
