### ISSUE TITLE
Update Smite - EAC not working

### ISSUE THREAD

**Issue by dboisvert** [Starz0r/AreWeAntiCheatYet#338]
### Game Title

SMITE

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention

https://www.theverge.com/2021/10/5/22709918/valve-steam-deck-supported-games-anti-cheat-proton-eac-battleye-epic

**Comment by doogie544** [comment]
Opps I duplicated this issue but I also provided logs as sources so I will link it here for more info.  Unfortunately the OP is correct, despite the files needed for wine/proton compatibility being added, the support was not actually turned on.

I think just a link showing the files added are not enough verification.  I think if someone provides a link to steamdb showing files added the status of the game should not be changed until logs are provided to prove eac is actually working to prevent more erroneous statuses on the main page.

 Here is a link to my report for more info
 
 
 https://github.com/Starz0r/AreWeAntiCheatYet/issues/340
