### ISSUE TITLE
Update: Apex Legends - game specific fix added to proton 7?

### ISSUE THREAD

**Issue by smintman** [Starz0r/AreWeAntiCheatYet#345]
### Game Title

Apex legends

### Status of the Anti-Cheat

🎉 Confirmed

### Proof of Mention

https://github.com/ValveSoftware/Proton/commit/25a58123a169dec4282b92bc1b24411278d0b65f

**Comment by doogie544** [comment]
No. 

That commit has nothing to do with EAC it has to do with disabling fsync and esync. 

Besides that, any thing added to proton does not enable EAC in any specific game that has to be done by the developers of the game. 

Even if they had added the proton specific EAC files do it the game still is not mean that EAC proton support has actually been enabled as has recently been evidenced by smite. 

That particular addition to proton is in no remote way relevant to EAC and even if it was adding a particular fix to proton does not enable EAC in a game

**Comment by smintman** [comment]
To be honest this isn't a game I play, but can it be played without EAC at all? if not then the evidence of a game specific fix just to get it running ok in proton, is at least a potential ray of hope that EAC support is coming?

**Comment by doogie544** [comment]
I don't play it either so I'm not sure about being able to play in private matches without EAC but I didn't think it was. 

It's possible that I'm wrong there but still at this point that wouldn't apply to the scope of the project yet. This project is to track working anti cheats not whether the game will run in some capacity with the anti-cheat disabled. 

I agree it certainly a ray of hope that may be valve knows something the rest of us don't especially considering there was a tweet that I saw today talking about Star wars squadrons and some other game that now has EAC working with a teaser about more to come soon.

**Comment by Rafii2198** [comment]
A small update, if you didn't know already, there is private branch for Apex on steam called `Steam Deck` with description `Steam Deck Testing` so I think we will get support before Monday.
Here's the branch: https://steamdb.info/app/1172470/depots/?branch=steam_deck (its private tho)
