### ISSUE TITLE
Update Intruder

### ISSUE THREAD

**Issue by ChildishGiant** [Starz0r/AreWeAntiCheatYet#348]
### Game Title

Intruder

### Status of the Anti-Cheat

🚫 Denied

### Proof of Mention

https://discord.com/channels/103933666417217536/103933666417217536/932059302515068989

**Comment by Starz0r** [comment]
Is it possible to get a screenshot for those who are unable or do not want to join the Discord?

**Comment by ChildishGiant** [comment]
![image](https://user-images.githubusercontent.com/13716824/154804088-77eefcbb-a8c5-4877-963a-cc36b60b33d9.png)
From a developer, through a mod in the official discord

**Comment by ChildishGiant** [comment]
Any thoughts?

**Comment by Starz0r** [comment]
Changed the status to `🚫 Denied` as per d39ce2d.

Unfortunate that it looks that the developer is misled into believing its more than just checking a box at this point. Hopefully they change their mind.
