### ISSUE TITLE
Dying Light 2: Stay Human

### ISSUE THREAD

**Issue by PieterWaegeman** [Starz0r/AreWeAntiCheatYet#353]
### Game Title

Dying Light 2: Stay Human

### Game Website

https://dl2.dyinglightgame.com/

### Anti-Cheat Software

Other

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention

https://www.gamingonlinux.com/2022/02/dying-light-2-stay-human-is-out-and-works-well-on-linux/

**Comment by Mar0xy** [comment]
This game indeed has no anti-cheat what it does have is denuvo drm which I guess sorta has a small anti-cheat built-in.

**Comment by EvoXCX** [comment]
This game has no anti-cheat.

**Comment by PieterWaegeman** [comment]
The game has no built in Anti-Cheat. They use Valve's VAC for multiplayer\co-op. Denuvo DRM is indeed in the game, but that's a anti-piracy protection.

**Comment by Starz0r** [comment]
> The game has no built in Anti-Cheat. They use Valve's VAC for multiplayer\co-op. Denuvo DRM is indeed in the game, but that's a anti-piracy protection.

Is there a specific tell for knowing how the game uses VAC?

**Comment by MathiewMay** [comment]
This game does not use VAC.

**Comment by Curve** [comment]
This game does not use anticheat ([1](https://guidedhacking.com/resources/dying-light-2-cheat-engine-table-inventory-unlocker-more.493/), [2](https://www.unknowncheats.me/forum/3364477-post10.html))
