### ISSUE TITLE
Update Elden Ring

### ISSUE THREAD

**Issue by syntacticallyWrong** [Starz0r/AreWeAntiCheatYet#359]
### Game Title

Elden Ring

### Status of the Anti-Cheat

🎉 Confirmed

### Proof of Mention

https://steamdb.info/app/1245620/history/?changeid=14059872

**Comment by vscsilva** [comment]
![image](https://user-images.githubusercontent.com/64592232/155884690-8654c6a8-8fa4-41fd-bd18-25c1c678f851.png)


Work flawlessly

**Comment by Celsiusss** [comment]
@Starz0r Should be "Supported", the game is already working with EAC.

**Comment by shanefagan** [comment]
It still says confirmed rather than supported
