### ISSUE TITLE
<Apex Legends>

### ISSUE THREAD

**Issue by DerHalbGrieche** [Starz0r/AreWeAntiCheatYet#370]
### Game Title

Apex Legends

### Game Website

https://www.ea.com/de-de/games/apex-legends

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

⭐ Supported

### Proof of Mention

https://www.protondb.com/app/1172470

**Comment by doogie544** [comment]
Duplicate of

https://github.com/Starz0r/AreWeAntiCheatYet/issues/366
