### ISSUE TITLE
Apex Legends

### ISSUE THREAD

**Issue by jiriks74** [Starz0r/AreWeAntiCheatYet#371]
### Game Title

Apex Legends

### Game Website

https://www.ea.com/games/apex-legends

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

⭐ Supported

### Proof of Mention

https://steamdb.info/depot/1172471/

**Comment by jiriks74** [comment]
Search for easyanticheat_x64.so

**Comment by Curve** [comment]
Duplicate of #366
Can you guys please just look at the existing issues before making a new one

**Comment by jiriks74** [comment]
> Duplicate of #366 Can you guys please just look at the existing issues before making a new one Also please properly set the title for gods sake

Sorry, first time, didn't realize and forgot about some things. Closing at it's duplicate. I've just been through a match, everything works as expected.
