### ISSUE TITLE
Update Insurgency: Sandstorm

### ISSUE THREAD

**Issue by Chinchzilla** [Starz0r/AreWeAntiCheatYet#375]
### Game Title

Insurgency: Sandstorm

### Status of the Anti-Cheat

⭐ Supported

### Proof of Mention

https://www.reddit.com/r/linux_gaming/comments/t56f5r/insurgency_sandstorm_works_on_linux/

**Comment by Chinchzilla** [comment]
More proof : https://github.com/ValveSoftware/Proton/issues/1651#issuecomment-1050840724

https://steamcommunity.com/app/581320/discussions/0/3190241719896417734/

**Comment by eddysn0wden** [comment]
It stopped working after minutes for me, EAC violation. Nothing announced. No sign of intentional support on steamDB.

**Comment by Chinchzilla** [comment]
See my redit post, if you implemented some sort of workaround that previously worked or you're launching from NTFS, it won't work, you also have to force Proton Experimental.

**Comment by Chinchzilla** [comment]
How about this?

Insurgency: Sandstorm most probably uses EOS version of EAC. The workaround for proton is different

881b0a8a0220a8c284d/2324da9a1c0341eea4cf43c070760c75$ pwd
/home/chinchzilla/.steam/debian-installation/steamapps/compatdata/581320/pfx/drive_c/users/steamuser/AppData/Roaming/EasyAntiCheat/eb330869cd5f4881b0a8a0220a8c284d/2324da9a1c0341eea4cf43c070760c75
chinchzilla@chinchzilla-desktop:~/.steam/debian-installation/steamapps/compatdata/581320/pfx/drive_c/users/steamuser/AppData/Roaming/EasyAntiCheat/eb330869cd5f4881b0a8a0220a8c284d/2324da9a1c0341eea4cf43c070760c75$ ls
easyanticheat_linux_x86_x64.eac           loader.log
easyanticheat_linux_x86_x64.eac.metadata

![image](https://user-images.githubusercontent.com/92267798/157392944-737340ab-c9fc-4967-b106-1c219ed83c0f.png)

**Comment by fredfiggleh0rn** [comment]
It still isn't working for me on either Void or Arch Linux. I don't get kicked on Windows.

On Linux I get kicked with this error
![lhx2xawh6e581](https://user-images.githubusercontent.com/101295532/157544829-363760bd-8b86-4541-90e1-ac82f6f46645.jpg)
![Screenshot from 2022-03-09 16-05-44](https://user-images.githubusercontent.com/101295532/157544896-84684727-2972-4fcb-91f7-a1eea78e209c.png)

I've tried:
Proton 7
Proton Experimental
Proton Experimental (bleeding-edge)
Reinstalling Sandstorm
Force Sandstorm to high priority updating
Reinstalling Steam
Disable Steam overlay (even though it doesn't work anyway)
Validate game files
Checking for Steam Client updates

The general consensus seem to be that it's now working, and the evidence you provided is further proof, but I seem to in the small minority of people where it just is not working. It will work for a little while then just stop out the blue. I've never done the workarounds previous mentioned either. I also need to launch the game several times or it will get stuck on the Splash screen.
I'm not sure what it is but it has me stumped, I will just try again with next version of Proton.

**Comment by Curve** [comment]
> It still isn't working for me on either Void or Arch Linux. I don't get kicked on Windows.
> 
> On Linux I get kicked with this error
> ![lhx2xawh6e581](https://user-images.githubusercontent.com/101295532/157544829-363760bd-8b86-4541-90e1-ac82f6f46645.jpg)
> ![Screenshot from 2022-03-09 16-05-44](https://user-images.githubusercontent.com/101295532/157544896-84684727-2972-4fcb-91f7-a1eea78e209c.png)
> 
> I've tried:
> Proton 7
> Proton Experimental
> Proton Experimental (bleeding-edge)
> Reinstalling Sandstorm
> Force Sandstorm to high priority updating
> Reinstalling Steam
> Disable Steam overlay (even though it doesn't work anyway)
> Validate game files
> Checking for Steam Client updates
> 
> The general consensus seem to be that it's now working, and the evidence you provided is further proof, but I seem to in the small minority of people where it just is not working. It will work for a little while then just stop out the blue. I've never done the workarounds previous mentioned either. I also need to launch the game several times or it will get stuck on the Splash screen.
> I'm not sure what it is but it has me stumped, I will just try again with next version of Proton.

May be a dumb question but have you installed the EAC Proton Runtime?

**Comment by freddyfiggleh0rn** [comment]
![Screenshot from 2022-03-09 18-11-32](https://user-images.githubusercontent.com/101299970/157562296-efe5db9b-073e-4bd8-97c0-d901e42c2d95.png)
![Screenshot from 2022-03-09 18-11-51](https://user-images.githubusercontent.com/101299970/157562299-63d8044c-82cb-4712-b46f-af498d68a292.png)
![Screenshot from 2022-03-09 18-12-22](https://user-images.githubusercontent.com/101299970/157562300-b95b7de8-d963-40ea-9ef4-8857f43ac028.png)
![Screenshot from 2022-03-09 18-13-34](https://user-images.githubusercontent.com/101299970/157562302-6c53583d-bfc0-4b5b-a500-f8e43441dccd.png)
![Screenshot from 2022-03-09 18-15-23](https://user-images.githubusercontent.com/101299970/157562304-7541d0d6-e985-41f3-ab54-0a4e0a0db90b.png)
![Screenshot from 2022-03-09 18-23-20](https://user-images.githubusercontent.com/101299970/157562306-b90c98f2-17c1-40cf-9f67-8b8e9e452b2b.png)

**Comment by freddyfiggledoop** [comment]
![Screenshot from 2022-03-09 18-29-27](https://user-images.githubusercontent.com/101300329/157562800-739bdea4-9572-4401-a043-6d0b5a7f22e5.png)

**Comment by Chinchzilla** [comment]
> ![Screenshot from 2022-03-09 18-29-27](https://user-images.githubusercontent.com/101300329/157562800-739bdea4-9572-4401-a043-6d0b5a7f22e5.png)

Have you been able to locate the EAC linux file like I did in your system?

**Comment by vscsilva** [comment]
Tried first with proton experimental (regular branch) and the game didn´t launch. Tried again with proton experimental bleeding edge branch and now the game works but I got kicked out.

![image](https://user-images.githubusercontent.com/64592232/160824553-7b360c32-6863-41d0-9a40-a4adfce76fce.png)

**Comment by Chinchzilla** [comment]
> Tried first with proton experimental (regular branch) and the game got stuck at this: ![image](https://user-images.githubusercontent.com/64592232/160825200-4c01c60c-a05b-4f09-896a-9613e5481142.png)
> 
> Tried again with proton experimental bleeding edge branch and now the game works but I got kicked out.
> 
> ![image](https://user-images.githubusercontent.com/64592232/160824553-7b360c32-6863-41d0-9a40-a4adfce76fce.png)
> 
> Edit: Installed EAC Runtime and got stuck again (see first screenshot)
> 
> Edit2: Unistalled everything and installed again (even EAC Runtime) and now the game works!

Thank you for confirmation! I play it for a month now without an issue, also if you browse reviews on steam, they are thanking NWI for enabling EAC for Linux

**Comment by Chinchzilla** [comment]
@Starz0r it seems to be working, there are plenty of steam reviews praising linux support, can we label it as supported?
