### ISSUE TITLE
Apex Legends not supported anymore

### ISSUE THREAD

**Issue by jiriks74** [Starz0r/AreWeAntiCheatYet#379]
### Game Title

Apex Legends

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

:grey_question: Unconfirmed

### Proof of Mention

https://steamdb.info/depot/1172471/

**Comment by jiriks74** [comment]
The file `easyanticheat_x64.so` was deleted, therefore, the game no longer supports Proton

**Comment by Curve** [comment]
This does not imply denied.

**Comment by jiriks74** [comment]
> This does not imply denied.

Sorry, I missclicked

**Comment by jiriks74** [comment]
Closing this issue as another update pushed 8 hours ago which has the .so file 0resent
