### ISSUE TITLE
<Far Cry 3>

### ISSUE THREAD

**Issue by DuplexEagle** [Starz0r/AreWeAntiCheatYet#408]
### Game Title

Far Cry 3

### Game Website

https://www.ubisoft.com/en-au/game/far-cry/far-cry-3

### Anti-Cheat Software

Other

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention

N/A

**Comment by Curve** [comment]
I don't think this game uses any anti-cheat

**Comment by Curve** [comment]
I could not find any information suggesting that the game uses any sort of anti cheat
