### ISSUE TITLE
<Far Cry 4>

### ISSUE THREAD

**Issue by DuplexEagle** [Starz0r/AreWeAntiCheatYet#409]
### Game Title

Far Cry 4

### Game Website

https://www.ubisoft.com/en-au/game/far-cry/far-cry-4

### Anti-Cheat Software

Other

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention

N/A

**Comment by Curve** [comment]
I could not find any information suggesting that the game uses any sort of anti cheat
