### ISSUE TITLE
<Grand Theft Auto IV>

### ISSUE THREAD

**Issue by DuplexEagle** [Starz0r/AreWeAntiCheatYet#414]
### Game Title

Grand Theft Auto IV

### Game Website

https://www.rockstargames.com/games/IV

### Anti-Cheat Software

Other

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention

N/A

**Comment by Faalagorn** [comment]
It used Games for Windows Live for Online back then, I'm not sure online works now at all?

**Comment by Bitwolfies** [comment]
Yeah, online doesnt work without mods anymore, dunno if it works on linux or not but its sure not apart of the real game.

**Comment by Starz0r** [comment]
The game doesn't seem to have an anti-cheat natively, and the only way to play multiplayer is through third-party patches. I don't think this game fits the qualification to be on the list.
