### ISSUE TITLE
<Ready or Not>

### ISSUE THREAD

**Issue by DuplexEagle** [Starz0r/AreWeAntiCheatYet#416]
### Game Title

Ready or Not

### Game Website

https://voidinteractive.net/

### Anti-Cheat Software

Other

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention

N/A

**Comment by Faalagorn** [comment]
I think it works on Proton including online?

**Comment by Starz0r** [comment]
This game does have multiplayer, but no versus mode, and no anti-cheat. If in the future it does get versus, and it comes with anti-cheat, please reopen this issue!
