### ISSUE TITLE
<The King of Fighter XV>

### ISSUE THREAD

**Issue by DuplexEagle** [Starz0r/AreWeAntiCheatYet#417]
### Game Title

The King of Fighter XV

### Game Website

https://www.snk-corp.co.jp/us/games/kof-xv/

### Anti-Cheat Software

Other

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention

N/A

**Comment by Curve** [comment]
I couldn't find any information suggesting the game uses any sort of anticheat
