### ISSUE TITLE
<Deep Rock Galactic>

### ISSUE THREAD

**Issue by DuplexEagle** [Starz0r/AreWeAntiCheatYet#418]
### Game Title

Deep Rock Galactic

### Game Website

https://www.deeprockgalactic.com/

### Anti-Cheat Software

Other

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention

https://steamcommunity.com/app/548430/discussions/1/154644349173729469/

**Comment by r2rX** [comment]
Been playing online sessions through Steam & Proton successfully, from December 2021 till now.

**Comment by Curve** [comment]
The game does not seem to use any anticheat ([1](https://www.reddit.com/r/DeepRockGalactic/comments/e62o0b/does_this_game_have_any_anticheat/), [2](https://www.reddit.com/r/DeepRockGalactic/comments/hscbn2/please_add_anticheat_to_the_game/fy9mde3/?context=3))
