### ISSUE TITLE
<Ice Station Z>

### ISSUE THREAD

**Issue by DuplexEagle** [Starz0r/AreWeAntiCheatYet#419]
### Game Title

Ice Station Z

### Game Website

https://store.steampowered.com/app/1795180/Ice_Station_Z/

### Anti-Cheat Software

Other

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention

N/A

**Comment by Curve** [comment]
I could not find any information that this game uses any anti-cheat, there is even an AntiCheat-Plugin which strongly suggests the game itself does not have any
