### ISSUE TITLE
Update Hell Let Loose

### ISSUE THREAD

**Issue by rokam** [Starz0r/AreWeAntiCheatYet#421]
### Game Title

Hell Let Loose

### Status of the Anti-Cheat

🎉 Confirmed

### Proof of Mention

https://steamdb.info/depot/686811/

**Comment by rokam** [comment]
EAC .so file is inside the active depot

**Comment by hcsubser** [comment]
It has been there for a month and a half, but according to protondb.com it is not working
https://www.protondb.com/app/686810

**Comment by rokam** [comment]
I know that, but just to add the file means it is confirmed.

**Comment by Curve** [comment]
Added note on anti-cheat files being present, but listed game as broken
