### ISSUE TITLE
7 Days to Die, War Thunder and Ark anticheats already run natively on Linux

### ISSUE THREAD

**Issue by doogie544** [Starz0r/AreWeAntiCheatYet#43]
I am aware that "The Verge"  article mentions that Fun Pimps gave a vague comment about the game.  I am not sure what question the writers actually asked the devs.  I would suspect that is was something like "will your game work on the 
Steam Deck"  As the game has run on Linux since it was released (or very soon after)  it has always run with the native version of EAC.

As there is no need for the devs to enable the proton version of EAC I'm not sure it should be listed as such in the list.  It would be better if it was listed as confirmed or working already with a note that is already runs natively with EAC and maybe include a link back to the steam store page as a source.

This would increase the accuracy of the page as well as not giving the wrong impression about the game due to a mistake or oversight by the writer of the article.

This could also be applies to War Thunder as it already runs on linux natively.  In fact the way the reply from the Devs is worded it future leads  me to believe that the questions that was asked may have been specific to the steam deck not necessarily to anticheat.

This leaves Ark, while the way they worded the answer it appears that they are specifically going to enable the proton BE module.  However as they already have a native version that runs with battleye, maybe there should also be a footnote about the fact that it also already runs natively.  (albeit the native version is much rougher than the windows version and often is broken.  I suspect that when the module is enabled and working successfully the devs will take that as an opportunity to drop the native client)

Great project btw, thanks for your work to get people informed of the status of wine anticheat.  I would just hate for the slight mistakes of "The Verge"  article due to poor or incomplete research to also drag down the accuracy of your effort.

**Comment by Starz0r** [comment]
Apologies. I didn't want to give the article too much trust, or credit, but as of currently it's all I knew, and all I found. None of my friends play any of these games except War Thunder, and I probably should have asked them if they knew.

Thank you for correcting the record!

**Comment by Newbytee** [comment]
Ark is a bit dubious. The Linux port is an old version of Ark and you can't play with people running on Windows and such. Calling it "supported" is false advertising in my opinion.

**Comment by doogie544** [comment]
As I stated in my report it's rougher than the windows version in so far as it doesn't look as good graphically and may not run quite on par on the same system but it's been like it since it was in Early Access. I can understand why people might say it's abandoned because in the past it has been broken for weeks at a time after an update. It has been better recently and the updates haven't been breaking it or they've been very quick about getting it fixed but it's still not uncommon for the Linux update to be a day behind windows. I'm not going to be surprised if once the wine module is enabled that they don't officially drop Linux support but at the moment it's still running natively and is using native anti-cheat

Maybe there should be a third category of natively supported to avoid confusion so somebody doesn't download the windows version and 122 GB later realize that the proton version does not have BE support yet. If added of course the other two games I mentioned should be changed as well and when or if they enable the wine module could be changed to just confirmed

**Comment by rurigk** [comment]
7 Days to Die runs natively on linux but the performance is very bad
Thats why you may choose the windows version over the native version

7 Days to Die has cross-platform multiplayer anyway

**Comment by Cryotize** [comment]
Native Linux Version of ARK is unusable. Unstable, many graphical bugs, delayed updates, worse graphics overall, but AntiCheat Works. 

Although this doesn't matter anymore, see this Steamworks article: https://store.steampowered.com/news/group/4145017/view/3104663180636096966

I've tested it on offical and Battleye enabled unoffical Servers, it works flawlessly. ARK is propely supported now.

**Comment by doogie544** [comment]
> Native Linux Version of ARK is unusable. Unstable, many graphical bugs, delayed updates, worse graphics overall, but AntiCheat Works.
> 
> Although this doesn't matter anymore, see this Steamworks article: https://store.steampowered.com/news/group/4145017/view/3104663180636096966
> 
> I've tested it on offical and Battleye enabled unoffical Servers, it works flawlessly. ARK is propely supported now.

How well the game run is not relevant to this project,  The point of this project was to track anticheat.  The anticheat has always worked in Ark.   It was always "properly supported" by the anticheat

*With*  proton experimental and Steam Beta BE is working in proton now, that is correct.  I have not personally tested it but I have more than one report from other users saying that it works.

As an aside, "unusable" it not true.  I have over 2K hours in the state you insist is unusable.  Obviously the game is "usable", it may not meet your standards of perfection but that does not make it unusable.

**Comment by Cryotize** [comment]
I know that this is about tracking the anticheat status, but i still wanted to mention how bad the native build is. 

Also, i don't know what maps you play and what you consider as "usable", but Genesis Gen1 is by far the worst with missing Textures. Most of the ground is just gray squares and nothing else. I personally wouldn't call that "usable". 

And i have over 2.3k hours too, just as a side note...^^ It just seems like i have higher standards for "usable"

**Comment by doogie544** [comment]
tbf I have not played and of the genesis maps, they didn't interest me at all, so I cannot speak to any missing textures for those maps.  

I did not say the game played well, only that it was playable.  Being able to play with proton will be a great QOL improvement for the game as native is so poor but it is usable for all the other maps afaik.  The only thing the linux version had over windows was the lack of ground clutter so you could find eggs and death bags that would get easily lost in the grass on windows ;).  

Not to start a discussion that would be off topic here but I suspect that WC will use the proton compatibility as a result to drop the linux client.  Sad if we lose one more native game, but overall considering general state of the game on linux and the state of linux "support" we currently have, I'm honestly not sure it will really be "that"  much of a loss.  (I will be sure to turn my ground clutter off or down to almost 0 if that happens or I just move to proton for improved performance..)
