### ISSUE TITLE
Update <Rogue Company>

### ISSUE THREAD

**Issue by kassindornelles** [Starz0r/AreWeAntiCheatYet#444]
### Game Title

Rogue Company

### Status of the Anti-Cheat

⭐ Supported

### Proof of Mention

N/A

**Comment by kassindornelles** [comment]
Loading the EAC (EOS) module successfully.

 _(some users on non-flatpak Steam are reporting issues tho)_

**Comment by kassindornelles** [comment]
> Loading the EAC (EOS) module successfully.
> Played a few matches, no issues.
> 
> _(some users on non-flatpak Steam are reporting issues tho)_

**Comment by kassindornelles** [comment]
![image](https://user-images.githubusercontent.com/40970965/167237461-61c93a05-e941-4e3c-9ef0-62dfea9c050d.png)
https://modules-cdn.eac-prod.on.epicgames.com/modules/7c0a8a40ba4a47dd899eed51a8fbc3fe/96121167e10b4d578499a15276196fd4/linux32_64

**Comment by Curve** [comment]
The game does not load for me and the Linux Modules are not present in the games directory (On ArchLinux, tried Proton Experimental, Proton 7 and GE, have the EAC Runtime installed)

**Comment by Curve** [comment]
Ok I just tested it with the steam flatpak - That works.

From reading some gentoo forum posts I think this may be related to something with glibc, (I run arch but the gentoo forums were the only thing I could find that is related to this) - The flatpak uses glibc 2.33 and I have 2.35.

**Comment by pbogut** [comment]
Can confirm it works fine with flatpak steam, does not with repo one (ArchLinux)

**Comment by Curve** [comment]
For those interested there's some discussion going on here: https://github.com/anyc/steam-overlay/issues/313#issuecomment-1132808327

**Comment by ryao** [comment]
> ![image](https://user-images.githubusercontent.com/40970965/167237461-61c93a05-e941-4e3c-9ef0-62dfea9c050d.png)
> https://modules-cdn.eac-prod.on.epicgames.com/modules/7c0a8a40ba4a47dd899eed51a8fbc3fe/96121167e10b4d578499a15276196fd4/linux32_64

This seems to be what got them to turn on proton support:

https://www.reddit.com/r/RogueCompany/comments/ufblus/do_you_still_play_rc_on_nintendo_switch/i6u0ggu/

1. I posted links to documentation showing it was just a few clicks.
2. The head of rogue company development was pinged.
3. Support was turned on the following Friday.

Sadly, the EAC module is broken outside of Ubuntu 20.04 and flatpak. I am trying to figure out why. So far, I know that Arch, Gentoo and Ubuntu 22.04 all have some change that breaks the EAC module.

Anyway, marking this as supported is somewhat premature until we know more. If it is marked, a massive caveat that only native steam on Ubuntu 20.04 and flatpak steam are known to work is needed.

**Comment by Curve** [comment]
> > ![image](https://user-images.githubusercontent.com/40970965/167237461-61c93a05-e941-4e3c-9ef0-62dfea9c050d.png)
> > https://modules-cdn.eac-prod.on.epicgames.com/modules/7c0a8a40ba4a47dd899eed51a8fbc3fe/96121167e10b4d578499a15276196fd4/linux32_64
> 
> This seems to be what got them to turn on proton support:
> 
> https://www.reddit.com/r/RogueCompany/comments/ufblus/do_you_still_play_rc_on_nintendo_switch/i6u0ggu/
> 
> 1. I posted links to documentation showing it was just a few clicks.
> 2. The head of rogue company development was pinged.
> 3. Support was turned on the following Friday.
> 
> Sadly, the EAC module is broken outside of Ubuntu 20.04 and flatpak. I am trying to figure out why. So far, I know that Arch, Gentoo and Ubuntu 22.04 all have some change that breaks the EAC module.
> 
> Anyway, marking this as supported is somewhat premature until we know more. If it is marked, a massive caveat that only native steam on Ubuntu 20.04 and flatpak steam are known to work is needed.
> 

I'll revert [this](https://github.com/Curve/areweanticheat/commit/d437764f7d595c65fd58c5ddfc7b78f40066f6cb) then and mark it as running instead

**Comment by ryao** [comment]
https://twitter.com/RogueCompany/status/1532817764532076544

Now Rogue Company is officially advertising Steam Deck support.
