### ISSUE TITLE
Update CRSED FOAD

### ISSUE THREAD

**Issue by JEZZADJ** [Starz0r/AreWeAntiCheatYet#451]
### Game Title

CRSED FOAD

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

⭐ Supported

### Proof of Mention

https://steamdb.info/app/884660/

**Comment by againstalllogic1** [comment]
It still doesn't work. No announcement. It was most likely listed on accident

https://user-images.githubusercontent.com/106219913/170176492-7423462e-b2e6-4903-ad5d-4e38467f533b.mp4

**Comment by Curve** [comment]
The game added a native Linux version, that doesn't work?
