### ISSUE TITLE
Website Insecure

### ISSUE THREAD

**Issue by SeanRamey** [Starz0r/AreWeAntiCheatYet#454]
If you click on any of the games, it opens an insecure link and can't be viewed. Please fix this.

**Comment by Curve** [comment]
![image](https://user-images.githubusercontent.com/37805707/170085864-9bd6af95-cdef-4c2b-bc74-09c0d41bd569.png)
I'm not sure what you mean

**Comment by Curve** [comment]
I cannot reproduce this and all of the reference links use https, I'll mark this as closed.

If you have any further issues regarding this please reopen ^^
