### ISSUE TITLE
[Suggestion] Change status to actually represent current game compatibility.

### ISSUE THREAD

**Issue by SeanRamey** [Starz0r/AreWeAntiCheatYet#455]
Instead of reporting what the developers said they would do, actually report what state the game currently is in. Kinda useless to say what the developers said, if they don't actually do it. Like that, all they have to do to make the entire list "confirmed" is say, "Yes we will fix anti-cheat support for linux" and never actually do it.

IMO, the "support level options" should be "Working, Not Working, or Partially Working" with seperate information that can say if there are confirmed plans to get it working.

**Comment by Curve** [comment]
The redesign features a "running" state, with additional notes

You can see an old version of the redesign here: https://curve.github.io/areweanticheat/
