### ISSUE TITLE
Mark Genshin Workaround as dangerous

### ISSUE THREAD

**Issue by wyndon** [Starz0r/AreWeAntiCheatYet#461]
With 75d928bb878602d574ab9c390fe54754f1daba40, Genshin Impact was marked as "Running" where it's not.

The only way to play Genshin Impact currently on Linux is to disable the anticheat with some tinkering.

**Comment by wyndon** [comment]
> It runs online and offline with the patch, it is explicitly marked as running because it requires tinkering and is not officially supported

What do you mean by offline? Genshin Impact is an online-only game.

Didn't see the definition, thanks. Guess I can close.

**Comment by Curve** [comment]
> > It runs online and offline with the patch, it is explicitly marked as running because it requires tinkering and is not officially supported
> 
> What do you mean by offline? Genshin Impact is an online-only game.
> 
> Didn't see the definition, thanks. Guess I can close.

I meant more or less offline - yes it always runs online but I just wanted to differentiate between coop and non coop ^^

**Comment by atomicptr** [comment]
I really don't think circumventing the anti cheat which might get users banned (yeah I'm risking it too...) should be advertised as "Running". At least not without some clear warnings.

**Comment by Curve** [comment]
> I really don't think circumventing the anti cheat which might get users banned (yeah I'm risking it too...) should be advertised as "Running". At least not without some clear warnings. 

I marked it as running because if you want to, the public resources to get it running more or less smoothly are easily accessible

I've explicitly not stated which patch is required to get the game running as to not to bring attention to the patch. 

If users want to find out how to run Genshin they'd need to do some research to stumble upon the patch and will then probably see what risks the patch brings

**Comment by cybik** [comment]
It might be overkill just for one case, but as a dumb idea, a red icon with a Dragon in it for "Here there be dragons", with "Dangerous" as its descriptor, would make sense here.

Like, it's not that it doesn't work, it's that if you don't know what it entails you REALLY shouldn't run it.

**Comment by Curve** [comment]
> It might be overkill just for one case, but as a dumb idea, a red icon with a Dragon in it for "Here there be dragons", with "Dangerous" as its descriptor, would make sense here.
> 
> Like, it's not that it doesn't work, it's that if you don't know what it entails you REALLY shouldn't run it.

Yeah that might be good too, I've spoken with Starz0r, and we came to the conclusion that we will mark the game as broken but will add a note stating that the game may run when using lutris (as lutris applies said patch)

**Comment by cybik** [comment]
> > It might be overkill just for one case, but as a dumb idea, a red icon with a Dragon in it for "Here there be dragons", with "Dangerous" as its descriptor, would make sense here.
> > Like, it's not that it doesn't work, it's that if you don't know what it entails you REALLY shouldn't run it.
> 
> when using lutris (as lutris applies said patch)

Additional nitpick: "Lutris or other means". I don't use Lutris, but the fundamental patchset is the same.

Obviously, the patchset itself should not be linked to.

**Comment by Curve** [comment]
Alright I've added more precise definitions for each state and moved Genshin to `Broken`, however I added a note that it does work when using dangerous patches, in this case patches that disable parts of the anticheat
