### ISSUE TITLE
Update Call of Duty Black Ops: Cold War

### ISSUE THREAD

**Issue by MathiewMay** [Starz0r/AreWeAntiCheatYet#462]
### Game Title

Call of Duty Black Ops: Cold War

### Status of the Anti-Cheat

😥 Broken

### Tinkering Steps

Add note: Broken due to DRM.

### Proof of Mention

N/A

**Comment by MathiewMay** [comment]
Well, the Treyarch Anti-Cheat is know to work on linux with all other titles, cold war uses the BattleNet DRM since they stopped releasing games on steam.

**Comment by MathiewMay** [comment]
Modern Warfare also uses BattleNet DRM, the only cod on BattleNet that does not use it is black ops 4 but i suspect that it is because when they first started development for bo4 it was supposed to be released on steam, then got pulled once development of the pc version was handed of to blizard.

**Comment by MathiewMay** [comment]
Well it could be the anti-cheat but that does not explain why bo4 works? unlesses bo4 had some special treatment from some linux people .

**Comment by Curve** [comment]
> Well it could be the anti-cheat but that does not explain why bo4 works? unlesses bo4 had some special treatment from some linux people .

BO4 porbably used an older anticheat

**Comment by MathiewMay** [comment]
bo4 is from 2018 and it just recently started working.

**Comment by MathiewMay** [comment]
lets just hope moder warfare and cold war can be the same soon enough.

**Comment by Curve** [comment]
If you don't mind I'd keep this open and later add modern warfare and cold war as broken (maybe due to anticheat)

**Comment by MathiewMay** [comment]
no problem

**Comment by Curve** [comment]
Nvm I was under the assumption that the game wasn't already on the list but due to it being listed as having ricochet I'd blame that for it not working on Linux
