### ISSUE TITLE
Reame Counter-Strike: Global Offensive​ (FACEIT)

### ISSUE THREAD

**Issue by MathiewMay** [Starz0r/AreWeAntiCheatYet#467]
### Game Title

Counter-Strike: Global Offensive​

### Status of the Anti-Cheat

🚫 Denied

### Tinkering Steps

Change game title from "[Counter-Strike: Global Offensive​](https://www.faceit.com/)" to "Faceit: CS:GO" or something like that, prevents confusion.

### Proof of Mention

N/A

**Comment by Curve** [comment]
@Starz0r and I have decided to name the entry the same and change the anticheat to faceit

@Starz0r Would you prefer a name change?

**Comment by Mar0xy** [comment]
This is more logical considering FACEIT isn't only CS:GO it also is TF2 and etc as it's its own application.

**Comment by Curve** [comment]
> This is more logical considering FACEIT isn't only CS:GO it also is for TF2 and Krunker since it's its own application.

This is true and also a reason why I didn't really want to list faceit at all since also it's probably never going to work on Linux (I mean support was even explicitly denied) - Maybe we should just remove faceit listings again

**Comment by Starz0r** [comment]
I think it's pretty clear what the entry is referring to, and it's not at all ambiguous. We could possibly add a note, or a hover tooltip specifically explaining it, but I think it's rather self documenting by its self. If by any chance this does cause confusion, then we can reopen a discussion to talk about specific solutions, but it's a bit premature to make any judgements on whether it's unclear or not.
