### ISSUE TITLE
Request Path Of Titans

### ISSUE THREAD

**Issue by dpanter** [Starz0r/AreWeAntiCheatYet#469]
### Game Title

Path Of Titans

### Game Website

https://pathoftitans.com/

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

⭐ Supported

### Tinkering Steps

Game in active development. 
Recently upgraded to Unreal Engine 5 - https://pathoftitans.com/blog/development-updates

### Proof of Mention

https://alderongames.com/store/path-of-titans

**Comment by Curve** [comment]
All I could find regarding the games anticheat suggests it uses battleye and not easy anticheat: https://pathoftitans.com/blog/anti-cheat-updates

**Comment by dpanter** [comment]
I've spoken with one of the devs (Matt) in the GamingOnLinux Discord, confirmed EAC. The game also works on his Steam Deck.
