### ISSUE TITLE
Counter Strike: Global Offensive's anti-cheat is listed as FACEIT, when it actually uses VAC, and supports linux and Steam Deck

### ISSUE THREAD

**Issue by CosmicIsCool** [Starz0r/AreWeAntiCheatYet#483]
### Game Title

Counter Strike: Global Offensive

### Status of the Anti-Cheat

⭐ Supported

### Tinkering Steps

Use launch options: %command% -nojoy -vulkan

### Proof of Mention

https://www.protondb.com/app/730

**Comment by Starz0r** [comment]
We currently have two entries for CS:GO, one with VAC, which is listed as Supported and Native, and one with the FACEIT anti-cheat, which is entirely unsupported and Denied by the developers. If you look up above the FACEIT entry, you will see the normal entry, and it is already listed as Supported.

**Comment by Curve** [comment]
On another note: Please **do not** provide tinkering steps for games that don't explicitly need them to function
