### ISSUE TITLE
Request: SCP: Secret Laboratory

### ISSUE THREAD

**Issue by BulletBlaster** [Starz0r/AreWeAntiCheatYet#498]
### Game Title

SCP: Secret Laboratory

### Game Website

https://scpslgame.com/

### Anti-Cheat Software

Other

### Status of the Anti-Cheat

⭐ Supported

### Tinkering Steps

The bleeding-edge branch of Proton Experimental

### Proof of Mention

https://github.com/ValveSoftware/Proton/releases/tag/proton-7.0-1

**Comment by Curve** [comment]
Are you sure the game works?

https://www.protondb.com/app/700330#lFAi9NdOla

ProtonDB reports seem to imply that it doesn't currenty

**Comment by BulletBlaster** [comment]
According to https://github.com/ValveSoftware/Proton/issues/4229 it works with the bleeding-edge branch of Proton Experimental

**Comment by Curve** [comment]
> According to https://github.com/ValveSoftware/Proton/issues/4229 it works with the bleeding-edge branch of Proton Experimental

Reports there are older than the linked protondb port, I'll try it out myself soon

**Comment by Curve** [comment]
Alright can confirm it works.

Just tested it, worked out of the box with proton experimental

**Comment by ImperatorStorm** [comment]
This should probably be downgraded to Running, as SCP-SL breaks proton regularly and Proton is officially unsupported by Northwoods.

**Comment by Curve** [comment]
> This should probably be downgraded to Running, as SCP-SL breaks proton regularly and Proton is officially unsupported by Northwood.

Done!
