### ISSUE TITLE
Request Midnight Ghost Hunt

### ISSUE THREAD

**Issue by ZachAR3** [Starz0r/AreWeAntiCheatYet#511]
### Game Title

Midnight Ghost Hunt

### Game Website

https://midnightghosthunt.com/

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

⭐ Supported

### Tinkering Steps

Works fine mostly altough some crashes when selecting perks (atleast for me) which can be fixed by disabling 'Show Tooltip Videos' under Options > Gameplay.

### Proof of Mention

https://twitter.com/PlayMGH/status/1509950951398031367

**Comment by Curve** [comment]
What are the EAC Problems mentioned in the tweet?

Doesn't give the impression of Supported

**Comment by ZachAR3** [comment]
> 

That tweet was from before it was working at all. I haven't had any EAC issues with the game and most people on Proton DB agree. Maybe it only works on Flatpak like this Proton DB comment suggests and that's what they were referring too? But it runs on Steam Deck which correct me if I'm wrong but uses a form of distro steam. 

> (2 reports)
> 11 hours overall8 hours on Linux
> 2 months ago
> Tinker Steps:Switch to experimental, Changed configuration
> 
> Have to run flatpak steam in order for EAC module to load. Also, need to disable 'Show Tooltip Videos' under Options > Gameplay to prevent crashing in loadout select menus. Works flawlessly after that.
> Instability:Occasionally
> 
> Need to disable 'Show Tooltip Videos' under Options > Gameplay to prevent crashing in loadout select menus.
> ► Multiplayer
> Overall (online):Excellent

**Comment by Curve** [comment]
> > 
> 
> That tweet was from before it was working at all. I haven't had any EAC issues with the game and most people on Proton DB agree. Maybe it only works on Flatpak like this Proton DB comment suggests and that's what they were referring too? But it runs on Steam Deck which correct me if I'm wrong but uses a form of distro steam. 
> 
> > (2 reports)
> > 11 hours overall8 hours on Linux
> > 2 months ago
> > Tinker Steps:Switch to experimental, Changed configuration
> > 
> > Have to run flatpak steam in order for EAC module to load. Also, need to disable 'Show Tooltip Videos' under Options > Gameplay to prevent crashing in loadout select menus. Works flawlessly after that.
> > Instability:Occasionally
> > 
> > Need to disable 'Show Tooltip Videos' under Options > Gameplay to prevent crashing in loadout select menus.
> > ► Multiplayer
> > Overall (online):Excellent

Thanks.
The problem with flatpak is related to a glibc issue, it's currently being tracked in the "steam-overlay" repo

**Comment by ZachAR3** [comment]
No problem. Thanks for the quick feedback and the website is great!. Should I close the problem or will you when you add it?

**Comment by Curve** [comment]
I'll close it once it's done ^^

**Comment by ZachAR3** [comment]
Sounds good :D
