### ISSUE TITLE
With its EGS release, Fall Guys no longer works

### ISSUE THREAD

**Issue by CommandMC** [Starz0r/AreWeAntiCheatYet#524]
### Game Title

Fall Guys: Ultimate Knockout  
Note: Game title on EGS is just "Fall Guys"

### Status of the Anti-Cheat

😥 Broken

### Tinkering Steps

Without any manual tinkering, all you get is an EAC loading bar that fills up, but never closes

Running the game through Proton-GE (with set SteamGameId so it runs its protonfixes) or Wine-GE with manually applied protonfixes does start the game, but when trying to queue for a game, an error box is displayed:
![image](https://user-images.githubusercontent.com/34034631/174790004-98ec868e-a0c0-4093-9771-7e237bd5aec9.png)

I'm not sure about the status of the game on Steam, it might still be working there (but since it's no longer obtainable there, that's only a small comfort)

### Proof of Mention

Multiple people on the Heroic Games Launcher discord are reporting the same issue: https://discord.gg/UhfPnrcK2n

**Comment by Curve** [comment]
> Hm, seems like the EGS version works for some people
> I'll close this for now and look into it further

Can you try the game in flatpak?
May be a glibc issue
