### ISSUE TITLE
Update <Game Name Here>

### ISSUE THREAD

**Issue by orowith2os** [Starz0r/AreWeAntiCheatYet#533]
### Game Title

Halo: The Master Chief Collection

### Status of the Anti-Cheat

😥 Broken

### Tinkering Steps

Must delete AT LEAST the easyanticheat_x64.so file in <gamelibrarypath>/steamapps/common/Halo The Master Chief Collection/easyanticheat/ to be able to play the game (without multiplayer or achievements) 

### Proof of Mention

https://www.xda-developers.com/halo-mcc-broken-steam-deck/

**Comment by Etaash-mathamsetty** [comment]
they have attempted to support it, and guess what happened, it broke the entire game for linux users. So obviously microsoft reverted it

**Comment by Curve** [comment]
> they have attempted to support it, and guess what happened, it broke the entire game for linux users. So obviously microsoft reverted it clearly they want to support the deck but something they did went horribly wrong

Yes, this is also what's reflected in the Reference for the Status and the Recorded Updates.  
I will close this issue for now - If there's anything you'd like to further discuss feel free to reopen @orowith2os

**Comment by Curve** [comment]
Adding to this:

Until the "Recorded Updates" Tab was added we had a sort of hierarchy for the Game-States: Supported > Running > Planned > Denied > Broken

However we could theoretically mark Halo MCC as Broken and only have the Recorded Updates show that they apparently tried to support it at one point - However I think that would only induce more confusion and make things less organized

**Comment by orowith2os** [comment]
Maybe it would be possible to include multiple statuses? For example, have MCC show as Planned/Broken, so that people know it was attempted or will be, and is currently broken. This might be the best way of going about it, to not confuse people with the recorded updates.

**Comment by Curve** [comment]
> Maybe it would be possible to include multiple statuses? For example, have MCC show as Planned/Broken, so that people know it was attempted or will be, and is currently broken. This might be the best way of going about it, to not confuse people with the recorded updates.

I'm not sure if that's a good idea, it will make things look too crowded

Also I don't think Broken + Planned makes any sense because Planned strongly implies Broken - If it ain't broken why plan to enable Support?
