### ISSUE TITLE
Rust: Garry tweeted that EAC would be enabled "tomorrow" on the 28th. Rust Tweeted delay. See "tinkering steps."

### ISSUE THREAD

**Issue by sshMilkshake** [Starz0r/AreWeAntiCheatYet#546]
### Game Title

Rust

### Status of the Anti-Cheat

🕧 Planned

### Tinkering Steps

Tweet from Garry saying EAC update "tomorrow" on the 28th: https://twitter.com/garrynewman/status/1541773484015161347
Tweet from Rust saying that the update was to be delayed on the 29th: https://twitter.com/playrust/status/1542069218140721154

These two tweets lead me to believe that the EAC update MIGHT be on the 7th...

### Proof of Mention

https://twitter.com/garrynewman/status/1541773484015161347 & https://twitter.com/playrust/status/1542069218140721154

**Comment by Curve** [comment]
Nice news!
