### ISSUE TITLE
Halo Infinite

### ISSUE THREAD

**Issue by DTechGuy** [Starz0r/AreWeAntiCheatYet#56]
### Game Title

Halo Infinite 

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention

n/a

**Comment by yoyossef** [comment]
Halo Infinite does not ship Easy Anti-Cheat or any other known kernel-side AC (the game still doesn't run on Proton as of yet though, through the latest beta flights). They're going for their own solution, that might not involve a client side AntiCheat at all.

> Our anti-cheat philosophy is to make cheating more difficult in ways that don't involve kernel drivers or background services. We've done a lot of work securing the Slipspace engine and developing novel ways to protect and change the game to slow down cheat development. When people do cheat, we're focused on catching them through their behavior and not from data that we've harvested from their machines. Combating cheaters is an ever-evolving arms race, but we're making the tech investments needed today to continue the fight for years to come.

https://www.halowaypoint.com/en-us/news/inside-infinite-april-2021
