### ISSUE TITLE
Request: call of duty modern warfare(2019)

### ISSUE THREAD

**Issue by DarthNihilus1** [Starz0r/AreWeAntiCheatYet#580]
### Game Title

call of duty modern warfare(2019)

### Game Website

https://www.callofduty.com/modernwarfare

### Anti-Cheat Software

Other

### Status of the Anti-Cheat

😥 Broken

### Proof of Mention

https://www.reddit.com/r/linux_gaming/comments/jqoi2l/call_of_duty_modern_warfare_on_linux/

**Comment by DarthNihilus1** [comment]
The Anti cheat is specifically called RICOCHET Anti Cheat

**Comment by DarthNihilus1** [comment]
Also regarding the proof I haven't seen any update online since 2 years ago which is odd

**Comment by Curve** [comment]
![image](https://user-images.githubusercontent.com/37805707/178425671-bf876033-cddd-48f0-8853-cd9dd6878170.png)
The game is already on the page.

**Comment by DarthNihilus1** [comment]
Sorry it didn't show up for me when I searched!
