### ISSUE TITLE
Update Paladins

### ISSUE THREAD

**Issue by Tosoju** [Starz0r/AreWeAntiCheatYet#581]
### Game Title

Paladins

### Status of the Anti-Cheat

😥 Broken

### Tinkering Steps

Earlier Proton Experimental used to work with Paladins ([seen from Proton's official changelog](https://github.com/ValveSoftware/Proton/wiki/Changelog)), but many people (myself and others in the Paladins discord who run linux) have experienced EAC kicking linux players out. 

Apparently [EAC was updated so it borked Proton](https://old.reddit.com/r/linux_gaming/comments/vwrc73/is_paladins_borked_again_i_get_booted_into_games/)

### Proof of Mention

https://www.protondb.com/app/444090

**Comment by DevanPratt** [comment]
I heard this happened with the other Hi-Rez games too (Realm Royale and Smite)

**Comment by Curve** [comment]
You need to use steam as a flatpak this is probably the glibc issue as I described previously

**Comment by Curve** [comment]
> You need to use steam as a flatpak this is probably the glibc issue as I described previously

Let me know if that fixes it. I may try it myself if I have time but I'm pretty certain that's the issue

**Comment by Tosoju** [comment]
I just tested Paladins on Flatpak, still no dice, will try out that patch mentioned by GloriousEggroll

**Comment by Curve** [comment]
Alright thanks for confirming!

I'll add a note & update that the game is broken currently but will leave the status as is because I think that it will be fixed soon especially since the Proton Changelogs explicitly mentioned it as working so I'd guess it's not intentional

**Comment by ChildishGiant** [comment]
Why not update the status as well?

**Comment by Curve** [comment]
> Why not update the status as well?

I explained that in my previous comment, I don't think that changing the status every week is worth it, I'd rather push updates that document on breakages

**Comment by SuperSamus** [comment]
Paladins is still not working, the mistake seems to be from Valve's side.
https://github.com/ValveSoftware/Proton/issues/6062

**Comment by Curve** [comment]
> Paladins is still not working, the mistake seems to be from Valve's side.
> https://github.com/ValveSoftware/Proton/issues/6062


I will update the status as soon as I'm back from vacation
