### ISSUE TITLE
Request: Multiversus

### ISSUE THREAD

**Issue by Holden988** [Starz0r/AreWeAntiCheatYet#585]
### Game Title

Multiversus 

### Game Website

https://multiversus.com/en

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

😥 Broken

### Proof of Mention

https://www.protondb.com/app/1818750

**Comment by lolsniperftw** [comment]
The anti cheat is working fine here. (open beta)

And also verified that the .eac files are downloaded from epic's cdn

**Comment by Curve** [comment]
> The anti cheat is working fine here. (open beta)
> 
> And also verified that the .eac files are downloaded from epic's cdn and played a few matches against real players

What distro are you on?

Do you use the flatpak?

This game may suffer from the same glibc issue as Rogue Company

**Comment by lolsniperftw** [comment]
> What distro are you on?

Nobara 36 (based on F36)

> Do you use the steam flatpak?

Native

**Comment by lolsniperftw** [comment]
You could try the game for yourself, it is pretty easy to get early access to the open beta.

**Comment by lolsniperftw** [comment]
It seems the Rogue Company issue does not apply to this game since now users on protondb report the anti-cheat is working fine on many distros
