### ISSUE TITLE
Scum

### ISSUE THREAD

**Issue by lodriguez** [Starz0r/AreWeAntiCheatYet#59]
### Game Title

Scum

### Game Website

https://scumgame.com

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention

N/A

**Comment by MattyGWS** [comment]
I got an email response from SCUM devs regarding enabling anticheat when I reached out;

> Hello Matty Wyett-Simmonds,
> 
> The anti-cheat upgrade has nothing to do with the compatibility with the Linux operating system, the game is not compatible with Linux as of now and we do not have an ETA as to when it will be.
> 
> Unfortunately, we would still need to spend a significant amount of time to enable the game on Linux and that is not something that we have time for at the moment, hopefully in the future, we will be able to enable it.
> 
> Hopefully, we will be able to enable Linux to be supported for SCUM, unfortunately, at the moment, we are dealing with some higher-priority stuff so we don't have time to investigate the process to get it enabled, once we cover high-priority stuff this should be easier to do.
> 
> Good luck with your project as well, and it's nice to hear others from the industry like our game. :)
> 
> Best regards,
> xKiCkx
