### ISSUE TITLE
Insurgency: Sandstorm

### ISSUE THREAD

**Issue by Chinchzilla** [Starz0r/AreWeAntiCheatYet#60]
### Game Title

Insurgency: Sandstorm

### Game Website

https://www.focus-entmt.com/en-us/games/insurgency-sandstorm

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

❔ Unconfirmed

### Proof of Mention

N/A total radio silence from developers

**Comment by ryleu** [comment]
duplicates #3
Please check through the list of issues before making a new one next time.
