### ISSUE TITLE
VRChat just added EasyAntiCheat

### ISSUE THREAD

**Issue by lexd0g** [Starz0r/AreWeAntiCheatYet#608]
### Game Title

VRChat

### Status of the Anti-Cheat

⭐ Supported

### Proof of Mention

https://canary.discord.com/channels/189511567539306508/189511567539306508/1001189606894600293 (in vrchat discord, screenshot: https://media.discordapp.net/attachments/899313429054128168/1001190784483196948/unknown.png)

**Comment by lexd0g** [comment]
whoops, accidentally used the update game template instead of the request new one, as mentioned anticheat is EasyAntiCheat, website is https://vrchat.com/

**Comment by lolsniperftw** [comment]
The FAQ might be a better source: https://hello.vrchat.com/blog/vrchat-security-update

> Does this prevent people from playing VRChat on platforms like SteamOS on the Steam Deck? What about Linux via Proton?
No, we’ve tested this! EAC works fine on these platforms. Thanks to Valve and the Proton team for all their hard work.
