### ISSUE TITLE
Knockout City also available on steam

### ISSUE THREAD

**Issue by Etaash-mathamsetty** [Starz0r/AreWeAntiCheatYet#629]
Minor inaccuracy, but there should be a steam and epic icon next to knockout city
![image](https://user-images.githubusercontent.com/45927311/182501628-e551da2a-04a2-44bc-8c35-4b13614c50e2.png)
![image](https://user-images.githubusercontent.com/45927311/182501704-43339b9f-9fd1-45d8-a244-55102df7b73b.png)

**Comment by Curve** [comment]
See https://github.com/Starz0r/AreWeAntiCheatYet/issues/630#issuecomment-1203897313
