### ISSUE TITLE
Multiversus is also available on the Epic Games Store.

### ISSUE THREAD

**Issue by xxl1212** [Starz0r/AreWeAntiCheatYet#630]
### Game Title

Multiversus

### Status of the Anti-Cheat

⭐ Supported

### Proof of Mention

https://store.epicgames.com/en/p/multiversus

**Comment by Curve** [comment]
I'm currently on vacation but if you don't mind you can create a pull request that adds the missing epic store fields as described here:

https://github.com/Starz0r/AreWeAntiCheatYet/issues/559#issuecomment-1177982450
