### ISSUE TITLE
Update <Insurgency Sandstorm>

### ISSUE THREAD

**Issue by ghost** [Starz0r/AreWeAntiCheatYet#647]
### Game Title

Insurgency Sandstorm

### Status of the Anti-Cheat

😥 Broken

### Tinkering Steps

It barely worked at all to be considered "supported" to begin with but now it has stopped working altogether after the latest game update.
The spash screen attempts to start EAC then says "Failed to load the anti-cheat module"
Appears to be distro-wide, same error on both Fedora Gnome Wayland or Solus Budgie xorg

### Proof of Mention

https://steamcommunity.com/app/581320/discussions/0/3451465085383842211/

**Comment by Curve** [comment]
> ### Game Title
> 
> Insurgency Sandstorm
> 
> ### Status of the Anti-Cheat
> 
> 😥 Broken
> 
> ### Tinkering Steps
> 
> It barely worked at all to be considered "supported" to begin with but now it has stopped working altogether after the latest game update.
> The spash screen attempts to start EAC then says "Failed to load the anti-cheat module"
> Appears to be distro-wide, same error on both Fedora Gnome Wayland or Solus Budgie xorg
> 
> ### Proof of Mention
> 
> https://steamcommunity.com/app/581320/discussions/0/3451465085383842211/

Does the error also occur in the flatpak version of steam?

**Comment by bradleygit** [comment]
Seems to work fine for me, was able to start and play a few games without issue, working on Fedora Linux using proton experimental

**Comment by Curve** [comment]
Alright will close then. 
OP is probably affected by the glibc issue.
