### ISSUE TITLE
Update <League of Legends>

### ISSUE THREAD

**Issue by khewweifeng** [Starz0r/AreWeAntiCheatYet#648]
### Game Title

League of Legends

### Status of the Anti-Cheat

👍 Running

### Tinkering Steps

use Lutris to play LoL / Garena LoL 

here is my recording for Garena LoL = https://cdn.discordapp.com/attachments/915611663472918588/1005459451429535764/2022-08-06-123421.776513347_1.webm

lutris-ge-lol-7.14-1-x86_64

### Proof of Mention

https://github.com/nhubaotruong/league-of-legends-linux-garena-script/issues/40#issuecomment-1200259371

https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/7.14-GE-1-LoL

**Comment by khewweifeng** [comment]
https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/7.14-GE-1-LoL

**Comment by Curve** [comment]
Doesn't the linked repo cover most of the steps you need to take to make the game run?
(It has also been updated yesterday so it seems quite well maintained)

**Comment by khewweifeng** [comment]
> Doesn't the linked repo cover most of the steps you need to take to make the game run? (It has also been updated yesterday so it seems quite well maintained)

Just download in Lutris and play because Lutris will do all the work (this version is the most newbie friendly I guess)
