### ISSUE TITLE
Rumbleverse running

### ISSUE THREAD

**Issue by aaronamk** [Starz0r/AreWeAntiCheatYet#672]
### Game Title

Rumbleverse

### Status of the Anti-Cheat

👍 Running

### Tinkering Steps

Heroic Launcher with Wine-7.2-GE-2

### Proof of Mention

https://www.reddit.com/r/SteamDeck/comments/wo0n6l/rumbleverse_working_with_heroic_games_launcher/

**Comment by Etaash-mathamsetty** [comment]
I tried multiple times and it's not working with proton experimental and proton 7.0-4

**Comment by alvesvaren** [comment]
Works for me for like 2 minutes in game and then just shows up a network error and I get disconnected, but works fine with latest proton-ge (7-30)

**Comment by Arian8j2** [comment]
It doesn't work with proton-ge (7-30) too 😔, Got **Connection Lost** after 2-3 seconds in match.

**Comment by Curve** [comment]
I will close this issue then. Feel free to reopen / open a new one in case anything changes
