### ISSUE TITLE
Update Rainbow Six: Siege

### ISSUE THREAD

**Issue by papamikey** [Starz0r/AreWeAntiCheatYet#694]
### Game Title

Rainbow Six Siege

### Status of the Anti-Cheat

😥 Broken

### Tinkering Steps

https://discussions.ubisoft.com/topic/111054/linux-support-for-r6s?lang=en-US put this link on the page for people to voice support please!

### Proof of Mention

https://discussions.ubisoft.com/topic/111054/linux-support-for-r6s?lang=en-US

**Comment by Curve** [comment]
Thanks for the new link, was wondering where the thread that was linked in the gol thread went

**Comment by papamikey** [comment]
Ubisoft Forums have been shut down and transferred to the official Discord Server. Please update the link to the page on the discord server here: https://canary.discord.com/channels/863058244934696961/1090191984456646699 

![image](https://user-images.githubusercontent.com/97386118/235444309-5defd020-e314-45ec-a760-9622c80f0678.png)

![image](https://user-images.githubusercontent.com/97386118/235444479-272e8700-aa17-4227-a0d5-941ddfbc1f21.png)
