### ISSUE TITLE
Add Battalion: Legacy

### ISSUE THREAD

**Issue by ToRRent1812** [Starz0r/AreWeAntiCheatYet#697]
### Game Title

Battalion: Legacy

### Game Website

https://store.steampowered.com/app/489940/BATTALION_Legacy/

### Anti-Cheat Software

Other

### Status of the Anti-Cheat

👍 Running

### Proof of Mention

Lead dev confirmed on twitch stream the game no longer has EasyAntiCheat protection making Battalion fully playable with proton.

**Comment by Curve** [comment]
Is there any recording of said stream so that I could add it as a reference?

In case there isn't I'll just link this issue instead.

**Comment by ToRRent1812** [comment]
Unfortunately Brammer has vods disabled on twitch.
