### ISSUE TITLE
Fortnite uses both EAC and BattlEye.

### ISSUE THREAD

**Issue by SamPingu** [Starz0r/AreWeAntiCheatYet#70]
From the link below, you can see that Fortnite uses both Battleye and EAC. So support for WINE/Proton should be enabled in both EAC and BE as the game will run with either of those anti-cheats.
https://www.reddit.com/r/FortNiteBR/comments/al8mo5/comment/efc4dkl/?utm_source=share&utm_medium=web2x&context=3

**Comment by ryleu** [comment]
duplicates #33

**Comment by SamPingu** [comment]
Oh yeah its already been reported. Sorry.
