### ISSUE TITLE
Update <Phantasy Star Online 2>

### ISSUE THREAD

**Issue by JaneSmith** [Starz0r/AreWeAntiCheatYet#726]
### Game Title

Phantasy Star Online 2

### Status of the Anti-Cheat

Supported (NA); Broken (JP)

### Tinkering Steps

I think this entry needs to either be updated, or a separate game entry needs to be added.

Phantasy Star Online 2 has two separate versions: the Japanese version which has been around since 2012, and the NA version which recently launched in 2020.

The status of this game on the website shows "Supported". But in reality, it only works on the NA version. For whatever reason, the Japanese version has GameGuard configured such that it does NOT run on Linux. Therefore, the status shown on the website is misleading and not entirely correct. It should show something like: "Supported (NA); Broken (JP)".

This isn't only relevant for Japan-based players, but a large number of players around the world. As the Japanese version of the game has been around for 8 more years than the NA version, there are many players around the world playing on the Japanese version. There are lots of tools to support this, with translation patches into different languages, etc.

So I ask that this please be updated.

### Proof of Mention

https://old.reddit.com/r/PSO2NGS/comments/ua5gf5/deleted_by_user/i5xfd16/

**Comment by Curve** [comment]
Good insight, thanks. 
I'll go with two separate entries
