### ISSUE TITLE
Halo MCC Minor Update

### ISSUE THREAD

**Issue by GlenMerlin** [Starz0r/AreWeAntiCheatYet#742]
### Game Title

Halo Master Chief Collection

### Status of the Anti-Cheat

🕧 Planned

### Proof of Mention

https://steamdb.info/patchnotes/9367265/

**Comment by Curve** [comment]
> I'm making this issue because the latest update puts more progress. The game once again launches with EAC enabled however upon starting the game a "EAC hash error" occurs and it is disabled.
> 
> They atleast fixed the crashing but it appears to still be disabled on their backend

Is the hash error glibc related? Does it work in the steam flatpak?

**Comment by GlenMerlin** [comment]
Not sure. Other EAC games appear to work fine on my system but I'll spin it up in the flatpak and give it a try

**Comment by GlenMerlin** [comment]
Just checked the issue does still happen on the flatpak version so I don't think it's glibc related

**Comment by Curve** [comment]
> Just checked the issue does still happen on the flatpak version so I don't think it's glibc related

Thanks for confirming
