### ISSUE TITLE
Update <Rumbleverse>

### ISSUE THREAD

**Issue by khewweifeng** [Starz0r/AreWeAntiCheatYet#760]
### Game Title

Rumbleverse

### Status of the Anti-Cheat

👍 Running

### Tinkering Steps

https://youtu.be/HK5EsELuOus?t=556

work ootb heroic games launcher https://discordapp.com/channels/812703221789097985/812703222232776726/1009024670005215272

### Proof of Mention

https://youtu.be/HK5EsELuOus?t=556

**Comment by Curve** [comment]
Why was this closed?

**Comment by khewweifeng** [comment]
> Why was this closed?

I tried the youtube guide, it does not work 

so I close this

**Comment by Curve** [comment]
> > Why was this closed?
> 
> I tried the youtube guide, it does not work 
> 
> so I close this 

What about working ootb in heroic?

Did others also report it not working?

**Comment by khewweifeng** [comment]
Yes, tried with heroic, still not working 


Sent from Workspace ONE Boxer 


On 12 Sep 2022 4:51 am, Noah ***@***.***> wrote: 

Why was this closed?

I tried the youtube guide, it does not work

so I close this

What about working ootb in heroic?

Did others also report it not working?

**Comment by Curve** [comment]
> Yes, tried with heroic, still not working 
> 
> 
> Sent from Workspace ONE Boxer 
> 
> 
> On 12 Sep 2022 4:51 am, Noah ***@***.***> wrote: 
> 
> Why was this closed?
> 
> I tried the youtube guide, it does not work
> 
> so I close this
> 
> What about working ootb in heroic?
> 
> Did others also report it not working?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you modified the open/close state. Message ID: ***@***.***>
> 
> 

Alright, as i can't test it myself currently I'll close it

**Comment by khewweifeng** [comment]
It seems still not working after I tried the YouTube method (heroic) 




Sent from Workspace ONE Boxer 


On 11 Sep 2022 3:39 am, Noah ***@***.***> wrote: 

Why was this closed?
