### ISSUE TITLE
Shatterline

### ISSUE THREAD

**Issue by MrGaidar** [Starz0r/AreWeAntiCheatYet#777]
### Game Title

Shatterline

### Game Website

https://www.shatterline.gg

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

😥 Broken

### Tinkering Steps

There is also a post on ProtonDB saying that dev team has said, on Discord, they are going to add support at sometime. Have not confirmed.

### Proof of Mention

https://www.protondb.com/app/2087030

**Comment by DevanPratt** [comment]
Looks like it works now according to some ProtonDB posts

**Comment by FSKiller** [comment]
Yeah it works! Needs manual intervention tho. Proton-GE-33 or Experimental & 
1) install d3dcompiler_47 with protontricks
2) set the wine Windows Version to Windows 7 otherwise you'll get connection error.

**Comment by Curve** [comment]
> Yeah it works! Needs manual intervention tho. Proton-GE-33 or Experimental & 
> 1) install d3dcompiler_47 with protontricks
> 2) set the wine Windows Version to Windows 7 otherwise you'll get connection error.

Great! Thanks

Will probably Update the games list in a few hours

**Comment by baryluk** [comment]
And it is now broken. Multiple people reporting issues with no workaround: https://www.reddit.com/r/linux_gaming/comments/xjl14y/cant_join_online_match_after_todays_shatterline/

**Comment by Curve** [comment]
> And it is now broken. Multiple people reporting issues with no workaround: https://www.reddit.com/r/linux_gaming/comments/xjl14y/cant_join_online_match_after_todays_shatterline/

Too bad, will update the status soon
