### ISSUE TITLE
Update Friday The 13th: The Game

### ISSUE THREAD

**Issue by illusionX3** [Starz0r/AreWeAntiCheatYet#781]
### Game Title

Friday The 13th: The Game

### Status of the Anti-Cheat

👍 Running

### Tinkering Steps

The game runs and works online on 6.3-8

### Proof of Mention

video proof: https://streamable.com/h0agl3 protondb report: https://www.protondb.com/app/438740#k8v0JyaD8l

**Comment by Curve** [comment]
Wow, great news :D!

**Comment by Curve** [comment]
Does it run out of the box apart from requiring a specific proton version?

**Comment by illusionX3** [comment]
yes
