### ISSUE TITLE
Add EAC supported game to the list

### ISSUE THREAD

**Issue by Domefemia** [Starz0r/AreWeAntiCheatYet#785]
### Game Title

Shatterline

### Game Website

https://www.shatterline.gg/

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

⭐ Supported

### Tinkering Steps

1) use proton-GE version 33
2) install d3dcompiler_47
3) set the wine Windows Version to Windows 7

### Proof of Mention

https://www.libreddit.de/r/linux_gaming/comments/xhs8e0/shatterline_has_enabled_eac_support_for_proton/

**Comment by Curve** [comment]
The game is already on the list.

It's marked as running due to some tinkering being required.
