### ISSUE TITLE
Add Gundam Evolution to the list (EAC)

### ISSUE THREAD

**Issue by Cherryda** [Starz0r/AreWeAntiCheatYet#804]
### Game Title

GUNDAM EVOLUTION

### Game Website

https://gundamevolution.com/en/

### Anti-Cheat Software

Easy Anti-Cheat

### Status of the Anti-Cheat

😥 Broken

### Proof of Mention

https://steamdb.info/tech/AntiCheat/EasyAntiCheat/

**Comment by Curve** [comment]
Duplicate of #786
