### ISSUE TITLE
Update Rust

### ISSUE THREAD

**Issue by Rainerr123** [Starz0r/AreWeAntiCheatYet#822]
### Game Title

Rust

### Status of the Anti-Cheat

😥 Broken

### Tinkering Steps

With this update the eac loading launcher has changed and you will get a "Disconnected: EAC: Client integrity violation" however if you change to "proton experimental" then start the game and load into a server you may be able to join an eac protected server. However you will be kicked after a minute or so.

### Proof of Mention

https://twitter.com/playrust/status/1575061791280971778

**Comment by Hiemerxd** [comment]
Also to note that while they did change over to the EOS Easy Anti Cheat, Garry Newman, the owner of facepunch posted this on twitter, saying they're basically unsure about if they want to support it at this point. [](https://twitter.com/garrynewman/status/1574466250167787520)

**Comment by Curve** [comment]
> Also to note that while they did change over to the EOS Easy Anti Cheat, Garry Newman, the owner of facepunch posted this on twitter, saying they're basically unsure about if they want to support it at this point. [https://twitter.com/garrynewman/status/1574466250167787520](https://twitter.com/garrynewman/status/1574466250167787520)

Thanks for the info!
