### ISSUE TITLE
Update Rust to Broken

### ISSUE THREAD

**Issue by Hiemerxd** [Starz0r/AreWeAntiCheatYet#825]
### Game Title

Rust

### Status of the Anti-Cheat

😥 Broken

### Tinkering Steps

Garry Newman, the owner of facepunch on twitter basically said that they are not sure if they want to support linux users at this point due to background issues, the twitter thread below shows the conversation and where they're at with it right now, seems like its teetering towards a No or Denied.

### Proof of Mention

https://twitter.com/garrynewman/status/1574466250167787520

**Comment by Curve** [comment]
I'd update the reference to your linked tweet, however I'll leave the status as is I think until we have a definitive no, I'd also like to change - the status to something along the lines of "Considering" but adding a new status for that isn't worth it, so I'll leave it as is and leave a note that they're having doubts.

Also, I'd appreciate if we could stick to one issue per game so please stick to #822 ^^
