### ISSUE TITLE
Linux user needs to host for easy anticheat to work Warhammer: Vermintide 2

### ISSUE THREAD

**Issue by sigboe** [Starz0r/AreWeAntiCheatYet#826]
### Game Title

Warhammer: Vermintide 2

### Status of the Anti-Cheat

👍 Running

### Tinkering Steps

Only works if a Linux user is the host. I have not tried two Linux users playing together.

### Proof of Mention

https://www.protondb.com/app/552500

**Comment by Curve** [comment]
Great news ^^
