### ISSUE TITLE
Add FIFA 23

### ISSUE THREAD

**Issue by jannis3005** [Starz0r/AreWeAntiCheatYet#827]
### Game Title

FIFA 23

### Game Website

https://www.ea.com/de-de/games/fifa/fifa-23

### Anti-Cheat Software

Other

### Status of the Anti-Cheat

🚫 Denied

### Proof of Mention

https://www.protondb.com/app/1811260

**Comment by Curve** [comment]
> ### Game Title
> 
> FIFA 23
> 
> ### Game Website
> 
> https://www.ea.com/de-de/games/fifa/fifa-23
> 
> ### Anti-Cheat Software
> 
> Other
> 
> ### Status of the Anti-Cheat
> 
> 🚫 Denied
> 
> ### Tinkering Steps
> 
> _No response_
> 
> ### Proof of Mention
> 
> https://www.protondb.com/app/1811260

Wow, out right blocking wine is just disappointing

**Comment by jannis3005** [comment]
> > ### Game Title
> > FIFA 23
> > ### Game Website
> > https://www.ea.com/de-de/games/fifa/fifa-23
> > ### Anti-Cheat Software
> > Other
> > ### Status of the Anti-Cheat
> > 🚫 Denied
> > ### Tinkering Steps
> > _No response_
> > ### Proof of Mention
> > https://www.protondb.com/app/1811260
> 
> Wow, out right blocking wine is just disappointing

Yeah, they don't even allow playing single player...

**Comment by Curve** [comment]
> > > ### Game Title
> > > FIFA 23
> > > ### Game Website
> > > https://www.ea.com/de-de/games/fifa/fifa-23
> > > ### Anti-Cheat Software
> > > Other
> > > ### Status of the Anti-Cheat
> > > 🚫 Denied
> > > ### Tinkering Steps
> > > _No response_
> > > ### Proof of Mention
> > > https://www.protondb.com/app/1811260
> > 
> > Wow, out right blocking wine is just disappointing
> 
> Yeah, they don't even allow playing single player...

Another EA moment
