### ISSUE TITLE
Escape from Tarkov, update from BattlEye

### ISSUE THREAD

**Issue by themadseventeen** [Starz0r/AreWeAntiCheatYet#859]
No change in the anti-cheat status (still planned), but BattlEye gave the update on the situation. The reason it's taking so long is because they are busy with the cheater situation.
The message is on the Tarkov Penguins discord.
https://discord.com/channels/891628783176650773/891636897179381781/1023454813297573958

**Comment by ultraSsak** [comment]
soon™

**Comment by rhysday** [comment]
This is closed? so Battleye works in Linux now? Or with upcoming patch?

**Comment by Curve** [comment]
> This is closed? so Battleye works in Linux now? Or with upcoming patch?

Battleye is "still working on it"

**Comment by Adrenocrom** [comment]
Tested an offline raid yesterday, works perfectly fine. If its works that would be awesome!

**Comment by Curve** [comment]
> Tested an offline raid yesterday, works perfectly fine. If its works that would be awesome!

I think offline raids and such work, but online play doesn't

**Comment by Adrenocrom** [comment]
Yes i red this on the board and i don't want to risk a ban, so i stay calm, util they say its ok to join.
But for testing out fps and graphics its nice to have.

**Comment by Faalagorn** [comment]
> Yes i red this on the board and i don't want to risk a ban, so i stay calm, util they say its ok to join. But for testing out fps and graphics its nice to have.

You don't risk a ban, you just can't join online raids, when you attempt to do that you are kicked out of Tarkov, but you can do all the hideout, stash and trading fine on Linux.

Sadly waiting for missing BattlEye implementation in Proton, that's up for BattlEye to update for Proton BattlEye runtime to add missing function Tarkov uses.

**Comment by Anaphylaxis** [comment]
gta 6 or battleye on linux?
