### ISSUE TITLE
Street Fighter 6 apparently will have support for the steam deck

### ISSUE THREAD

**Issue by Heus-Sueh** [Starz0r/AreWeAntiCheatYet#860]
### Game Title

Street Fighter 6

### Status of the Anti-Cheat

🕧 Planned

### Proof of Mention

https://twitter.com/Plagman2/status/1578571751696797696

**Comment by pbogut** [comment]
Is there any Anti-Cheat there though?

**Comment by Etaash-mathamsetty** [comment]
This should be counted as running, not planned, I have seen it working for multiple people on proton-ge discord and now on twitter

**Comment by pbogut** [comment]
If it doesn't use any anticheat it should not even be here.

**Comment by Curve** [comment]
So... does it use any Anti-Cheat?

**Comment by Curve** [comment]
Closing this as I can't find information about the games Anti-Cheat.
