### ISSUE TITLE
Update Crossout

### ISSUE THREAD

**Issue by Krafting** [Starz0r/AreWeAntiCheatYet#866]
### Game Title

Crossout

### Status of the Anti-Cheat

👍 Running

### Tinkering Steps

The game now runs fine, support for EAC on linux seems to be present.

I didn't find any mention of that in the Steam News or anywhere sadly, but Valve put the Playable Steam Deck status on the game. 

### Proof of Mention

https://www.protondb.com/app/386180

**Comment by Etaash-mathamsetty** [comment]
Awesome, Will give it a shot

**Comment by Etaash-mathamsetty** [comment]
this should be "Supported" rather than "running" the devs intentionally put the EAC .so file in place for proton users.
