### ISSUE TITLE
totally accurate battlegrounds denied

### ISSUE THREAD

**Issue by nanopone** [Starz0r/AreWeAntiCheatYet#900]
### Game Title

Totally Accurate Battlegrounds

### Status of the Anti-Cheat

🚫 Denied

### Tinkering Steps

landfall have said in a twitter reply that equ8 does not support being used in proton and that they have no plans to change the anti-cheat they're using at this time

### Proof of Mention

https://twitter.com/LandfallGames/status/1583343808817016834

**Comment by Curve** [comment]
Doesn't splitgate also use equ8?
Or does splitgate explicitly disable the AntiCheat on Linux?

**Comment by ImUrX** [comment]
EQU8 mentions no linux support on their [FAQ](https://www.equ8.com/faq), I haven't played splitgate on linux but isnt it native?

**Comment by Curve** [comment]
> EQU8 mentions no linux support on their [FAQ](https://www.equ8.com/faq), I haven't played splitgate on linux but isnt it native?

It is, however, as far as I'm aware, it uses equ8

**Comment by ImUrX** [comment]
Yeah that's what I'm saying, its the easiest thing to deduce XD. Let me check

**Comment by ImUrX** [comment]
I just checked, I didn't find anything with [``objdump -j .plt -S elffile | grep '\#'``](https://gist.github.com/ImUrX/378e88cf076815e1366287170810559b), neither I saw interesting shared objects. Not sure what they do

**Comment by Etaash-mathamsetty** [comment]
tbh I think splitgate's linux version is completely unprotected
