### ISSUE TITLE
Update Midnight Ghost Hunt (915810)

### ISSUE THREAD

**Issue by wizardlink** [Starz0r/AreWeAntiCheatYet#903]
### Game Title

Midnight Ghost Hunt

### Status of the Anti-Cheat

😥 Broken

### Tinkering Steps

Some people are having luck with Steam Flatpak, but most are not (including me, who's running Steam Flatpak).

Another detail, the status column of this game points to _SCP: Secret Laboratory_ and not the actual game's _ProtonDB_ page.

### Proof of Mention

https://www.protondb.com/app/915810

**Comment by Curve** [comment]
Thanks for the note!

Some games don't work when you're not using the flatpak, seeing though that they're running inside of the flatpak I consider it as running (with "workarounds")

**Comment by wizardlink** [comment]
> Thanks for the addotional note!
> 
> Some games don't work when you're not using the flatpak, seeing though that they're running inside of the flatpak I consider it as running (with "workarounds")

Then other games such as Genshin should be in the state of "Running" too, no? Because they work, but require workarounds, on top of being consistent unlike this case where the workaround does not works for me.

**Comment by Curve** [comment]
> > Thanks for the addotional note!
> > 
> > Some games don't work when you're not using the flatpak, seeing though that they're running inside of the flatpak I consider it as running (with "workarounds")
> 
> Then other games such as Genshin should be in the state of "Running" too, no? Because they work, but require workarounds, on top of being consistent unlike this case where the workaround does not works for me.

Oh also thanks for pointing out that it doesn't work for you inside the flatpak, that should count as broken then
