### ISSUE TITLE
Fortnite removed Hyperion/Byfron Anti-Cheat

### ISSUE THREAD

**Issue by FarmEquipment69** [Starz0r/AreWeAntiCheatYet#918]
### Game Title

Fortnite

### Status of the Anti-Cheat

🚫 Denied

### Tinkering Steps

Fortnite used to have FortniteLoader-Win64-Shipping.dll (Hyperion/Byfron) which decrypted FortniteClient-Win64-Shipping.exe, FortniteClient-Win64-Shipping.exe is now able to load in IDA and not encrypted.

### Proof of Mention

https://i.imgur.com/vxzsAqQ.png

**Comment by Curve** [comment]
Wow I wonder if that's actually intended

**Comment by Mash0Star** [comment]
I recorded what exactly happens in creative mode and uploaded it to Youtube: https://youtu.be/3ccDbD3NGTg
They had an error pop up every time you opened up Fortnite and it would crash your game soon after in the lobby yesterday, but now it has been fixed! 
(https://user-images.githubusercontent.com/43681827/199487810-66bb5d97-f522-4241-b0e7-bdc53a4794a1.png)
There's only like 1 glitch i can see and that is that the intro video tries to play, but it can't so it just shows a black screen. 
I really hope that Epic Games will make Fortnite playable on Linux.

**Comment by Etaash-mathamsetty** [comment]
I HAVE to try this, what if they actually enabled support

**Comment by Etaash-mathamsetty** [comment]
> > edit: got kicked on wine staging 7.20
> 
> We did not had success while using 7.20, but rather on the latest builds of Proton-GE (based on 7.19) instead.

I tried it with proton-ge 7-38 and now it's not working at all, let me try deleting the prefix

**Comment by Mash0Star** [comment]
This error pops up again now for some odd reason? (https://user-images.githubusercontent.com/43681827/199639804-59ebdbdd-1002-4e27-80af-ed383ee6dc1a.png)
And now it crashes in the lobby before i can even do anything.

**Comment by dragonDScript** [comment]
:(

**Comment by TheSudoer** [comment]
Game is running for me under ProtonGE 7-41 launched with the Heroic launcher, only problem being the game isn't stable and will crash often, that being said anti-cheat seems to be working.

**Comment by Etaash-mathamsetty** [comment]
> Game is running for me under ProtonGE 7-41 launched with the Heroic launcher, only problem being the game isn't stable and will crash often, that being said anti-cheat seems to be working.

did you play through a whole match or at least 5 mins of one?

**Comment by dragonDScript** [comment]
Do they ban you if they detect you are running the game on Linux?

**Comment by Etaash-mathamsetty** [comment]
> Do they ban you if they detect you are running the game on Linux?

I haven't been banned while I was experimenting, but they easily have the power to

**Comment by TheSudoer** [comment]
> 

I got into a game, jumped out of the battle bus, and the game window froze before closing with no mention of any anti-cheat error.

**Comment by Etaash-mathamsetty** [comment]
> > did you play through a whole match or at least 10 mins of one?
> > this game has been "running" for me like that (unstable and lots of crashing) since 2021, I used lutris wine 6.13 back then to run the game, in fact my friend was on and I joined his lobby and we chatted for like a few mins before telling him that I can't play the game due to it crashing bc of anti cheat
> 
> I got into a game, jumped out of the battle bus, and the game window froze before closing with no mention of any anti-cheat error.

that happens because of anti-cheat

**Comment by japa4551** [comment]
Tried running the game both via Lutris and Heroic Games, on both cases the game runs fine (other than some lag, but that's probably the shaders being cached) but it crashes a minute or two after jumping out of the bus. Like @Etaash-mathamsetty said its 50/50, it either crashes directly or it gives you the anti-cheat error then crashes

Tried both with ProtonGE 7.42 and Proton 7.22, also tried to use Steam's EAC Runtime with PROTON_EAC_RUNTIME but unfortunately i've got the same result.

**Comment by sfjuocekr** [comment]
EAC will now trigger a re-validation of game files after the boostrapper fails to load the Linux module and loads the NullClient.

You can get around the first check by simply clicking anywhere on the screen outside the notifcation, but the second time the game is force closed for the re-validation. If you trick the game into skipping the check, the game runs no problem! At least I was able to run around in the LEGO world, build and smash stuff without any issues. You are eventually kicked for the lack of EAC.

Any game deploying EAC without the Linux module enabled on the EAC Developer Portal is just discriminating, which is very sad in this age of inclusion.

**Comment by SingleInfiniteLoop** [comment]
Fortnite anti-tamper system always validated critical game files, including game launcher, game executable and anti-cheat loader executable files stored on disk, irregardless of whether anti-cheat is actually working. It is a system that works independently of anti-cheat one and is also activated alongside it.
The message about the need for the game to be restarted is displayed when one of the start-up checks made by the anti-tamper system has failed.
