### ISSUE TITLE
Clickable Status links should be either Black or URL Blue and standard text should be grey

### ISSUE THREAD

**Issue by Two-Tone** [Starz0r/AreWeAntiCheatYet#95]
The current way the status links are set up is the exact opposite of modern web design standards and is thus unintuitive.

**Comment by Starz0r** [comment]
Fixed in https://github.com/Starz0r/AreWeAntiCheatYet/commit/bb8cf6a7147b9c8d7bb8042612ee8c4b1e931c13!
