### ISSUE TITLE
Update Dead by Daylight

### ISSUE THREAD

**Issue by rokam** [Starz0r/AreWeAntiCheatYet#971]
### Game Title

Dead by Daylight

### Status of the Anti-Cheat

⭐ Supported

### Tinkering Steps

No tinkering needed

### Proof of Mention

https://www.reddit.com/r/linux_gaming/comments/z3j15h/i_was_able_to_play_dead_by_daylight_on_steam/

**Comment by Gustash** [comment]
> ### Game Title
> 
> Dead by Daylight
> 
> ### Status of the Anti-Cheat
> 
> ⭐ Supported
> 
> ### Tinkering Steps
> 
> No tinkering needed
> 
> ### Proof of Mention
> 
> https://www.reddit.com/r/linux_gaming/comments/z3j15h/i_was_able_to_play_dead_by_daylight_on_steam/

I would still keep it as Running, but remove the note that it may only work on Epic Games. 

We're still waiting for an official announcement of support, so we're not fully convinced this is not going to break with other patches. 

A better proof link would probably be [this](https://forum.deadbydaylight.com/en/discussion/comment/3274674/#Comment_3274674), which is from the official forum and has multiple replies confirming it working. 

Note that Steam still doesn't install Proton EasyAntiCheat Runtime as a dependency of DBD, so a manual install is still required for now. I believe this is another argument to not consider it "Supported" right now.

**Comment by Etaash-mathamsetty** [comment]
> > ### Game Title
> > Dead by Daylight
> > ### Status of the Anti-Cheat
> > star Supported
> > ### Tinkering Steps
> > No tinkering needed
> > ### Proof of Mention
> > [reddit.com/r/linux_gaming/comments/z3j15h/i_was_able_to_play_dead_by_daylight_on_steam](https://www.reddit.com/r/linux_gaming/comments/z3j15h/i_was_able_to_play_dead_by_daylight_on_steam/)
> 
> I would still keep it as Running, but remove the note that it may only work on Epic Games.
> 
> We're still waiting for an official announcement of support, so we're not fully convinced this is not going to break with other patches.
> 
> A better proof link would probably be [this](https://forum.deadbydaylight.com/en/discussion/comment/3274674/#Comment_3274674), which is from the official forum and has multiple replies confirming it working.
> 
> Note that Steam still doesn't install Proton EasyAntiCheat Runtime as a dependency of DBD, so a manual install is still required for now. I believe this is another argument to not consider it "Supported" right now.

it should be considered as supported since the .so file is present, so it is supported even if the devs didn't say anything about it, they literally had to put that .so file in there and that doesn't happen by accident

**Comment by Gustash** [comment]
That .so file has been there for almost a year at this point. That didn't mean the game ran at all, in fact, it didn't until a couple of days ago.

Considering they promised to support Linux, we should at least wait a bit for an official announcement. We haven't even heard anything from anyone in BHVR about the fact that it started working for EGS a week ago.

**Comment by Etaash-mathamsetty** [comment]
> That .so file has been there for almost a year at this point. That didn't mean the game ran at all, in fact, it didn't until a couple of days ago.
> 
> Considering they promised to support Linux, we should at least wait a bit for an official announcement. We haven't even heard anything from anyone in BHVR about the fact that it started working for EGS a week ago.

makes sense, yeah we should wait for an official announcement or something then, what if it's just the EAC grace period or something

**Comment by Gustash** [comment]
I don't believe it is because without Proton EAC Runtime it does kick you out saying it couldn't connect to EAC. So it seems like it is loaded properly, but until we get any official word on it, it could be just a coincidence

**Comment by Gustash** [comment]
This should be updated to `Planned` again at this point in time: https://forum.deadbydaylight.com/en/discussion/comment/3275908/#Comment_3275908

Seems like BHVR broke it again... Only worked for a day on Steam...

**Comment by Etaash-mathamsetty** [comment]
> This should be updated to `Planned` again at this point in time: https://forum.deadbydaylight.com/en/discussion/comment/3275908/#Comment_3275908
> 
> Seems like BHVR broke it again... Only worked for a day on Steam...

no the status shouldn't be changed, the epic version works just fine still

**Comment by Gustash** [comment]
> > This should be updated to `Planned` again at this point in time: https://forum.deadbydaylight.com/en/discussion/comment/3275908/#Comment_3275908
> 
> > 
> 
> > Seems like BHVR broke it again... Only worked for a day on Steam...
> 
> 
> 
> no the status shouldn't be changed, the epic version works just fine still

Does it? I've tried today and it fails to initialise EAC, even with the tweaks applied (PROTON_EAC_RUNTIME and linking EasyAntiCheat folder)

**Comment by Etaash-mathamsetty** [comment]
> > > This should be updated to `Planned` again at this point in time: https://forum.deadbydaylight.com/en/discussion/comment/3275908/#Comment_3275908
> > 
> > 
> > > 
> > 
> > 
> > > Seems like BHVR broke it again... Only worked for a day on Steam...
> > 
> > 
> > no the status shouldn't be changed, the epic version works just fine still
> 
> Does it? I've tried today and it fails to initialise EAC, even with the tweaks applied (PROTON_EAC_RUNTIME and linking EasyAntiCheat folder)

strange, just played a full match with no issues

**Comment by Curve** [comment]
Maybe a glibc issue again?
For those wo can't get it to work try to use the heroic games flatpak, maybe that helps 

(Background info: there were some issues with eac failing to initialize on some systems, the issue was traced back to a glibc update, which has since been fixed on all distros as far as I'm aware, however it shouldn't hurt to try the flatpak when you have an issue, as such dependencies are usually very stable there)

**Comment by Etaash-mathamsetty** [comment]
> Maybe a glibc issue again? For those wo can't get it to work try to use the heroic games flatpak, maybe that helps
> 
> (Background info: there were some issues with eac failing to initialize on some systems, the issue was traced back to a glibc update, which has since been fixed on all distros as far as I'm aware, however it shouldn't hurt to try the flatpak when you have an issue, as such dependencies are usually very stable there)

I am using arch linux btw, I have the latest glibc on it, I think that's not the problem

**Comment by Curve** [comment]
> > Maybe a glibc issue again? For those wo can't get it to work try to use the heroic games flatpak, maybe that helps
> > 
> > (Background info: there were some issues with eac failing to initialize on some systems, the issue was traced back to a glibc update, which has since been fixed on all distros as far as I'm aware, however it shouldn't hurt to try the flatpak when you have an issue, as such dependencies are usually very stable there)
> 
> I am using arch linux btw, I have the latest glibc on it, I think that's not the problem

No shouldn't be a problem then

**Comment by illusionX3** [comment]
Still works for me on Steam. When I reboot my computer and try to launch it, it fails EAC and crashes. I then start the game again and EAC initializes.

**Comment by aleksasiriski** [comment]
It should be updated as broken again...

**Comment by Curve** [comment]
> It should be updated as broken again...

Any references?
Seems to work for some - if so it may be an issue with some setups

**Comment by aleksasiriski** [comment]
A day after it started working they added a kick if you're on Linux. The game itself works but when trying to play multiplayer you get Error code 500. It's happening to [everyone](https://forum.deadbydaylight.com/en/discussion/282110/eac-on-steam-deck-proton-linux/p23)...

**Comment by aleksasiriski** [comment]
From the SAME thread you put on your website: ```Current EAC Status: Looks like we spoke too soon. While the game worked perfectly yesterday, 2022-11-24, on Steam with no tweaking, today 11-25 it's back to disconnecting us with error 500.```

**Comment by rokam** [comment]
We don't need to keep this open.

**Comment by Curve** [comment]
> From the SAME thread you put on your website: `Current EAC Status: Looks like we spoke too soon. While the game worked perfectly yesterday, 2022-11-24, on Steam with no tweaking, today 11-25 it's back to disconnecting us with error 500.`

Thanks for the reference!

**Comment by Curve** [comment]
> We don't need to keep this open.

I'll keep it open until I change the status to broken again

**Comment by Etaash-mathamsetty** [comment]
what if they were all trying the steam version, I tried the epic version the other day and it worked just fine, I will try it again

**Comment by aleksasiriski** [comment]
Steam version worked without workarounds, expect for installing EAC runtime, for a single day. After that, both Steam and Heroic broke (you can still do everything except join a multiplayer match)

**Comment by Etaash-mathamsetty** [comment]
> Steam version worked without workarounds, expect for installing EAC runtime, for a single day. After that, both Steam and Heroic broke (you can still do everything except join a multiplayer match)

Joining multiplayer was working fine for me though, super strange, will try it again today like I said

**Comment by aleksasiriski** [comment]
Joining multiplayer was working fine for everyone, for a single day on Steam, before that only on Heroic with workarounds. After that they added disconnects (error code 500) on the server side.

**Comment by Etaash-mathamsetty** [comment]
> Joining multiplayer was working fine for everyone, for a single day on Steam, before that only on Heroic with workarounds. After that they added disconnects (error code 500) on the server side.

I also stated earlier that playing a full match worked as well, but like I said, will try playing another full match

**Comment by Gustash** [comment]
@Etaash-mathamsetty were you able to test this on your side?

**Comment by Etaash-mathamsetty** [comment]
> @Etaash-mathamsetty were you able to test this on your side?

yes, the game is still working, played another full game

**Comment by aleksasiriski** [comment]
Arch Linux with Heroic Games?

**Comment by aleksasiriski** [comment]
It's kicking me with error 500 on Fedora Silverblue, Steam Flatpak.

**Comment by aleksasiriski** [comment]
> > @Etaash-mathamsetty were you able to test this on your side?
> 
> yes, the game is still working, played another full game (after 6.4.1 update)

Can you list all the modifications you made to make the game work?

**Comment by aleksasiriski** [comment]
I can't test it since I don't have Dead by Daylight on Epic, only Steam. Maybe someone else can?

**Comment by Etaash-mathamsetty** [comment]
> I can't test it since I don't have Dead by Daylight on Epic, only Steam. Maybe someone else can?

oh I forgot this game was paid game, I think I grabbed it for free a while back then (gotta focus on giving epic the lowest amount of money possible)

**Comment by aleksasiriski** [comment]
So {gameroot}/DeadByDaylight/Binaries/EGS is a symlink to {gameroot}/EastAntiCheat?

**Comment by Etaash-mathamsetty** [comment]
> So {gameroot}/DeadByDaylight/Binaries/EGS is a symlink to {gameroot}/EastAntiCheat?
{gameroot}/DeadByDaylight/Binaries/EGS/EastAntiCheat is linked to  {gameroot}/EastAntiCheat

**Comment by Curve** [comment]
> > I can't test it since I don't have Dead by Daylight on Epic, only Steam. Maybe someone else can?
> 
> oh I forgot this game was a paid game, I think I grabbed it for free a while back then (gotta focus on giving epic the lowest amount of money possible lol)

If it was a free game I think I may own it.
I'll take a look this week if I find the time to do so ^^

**Comment by aleksasiriski** [comment]
> > So {gameroot}/DeadByDaylight/Binaries/EGS is a symlink to {gameroot}/EastAntiCheat?
> 
> {gameroot}/EasyAntiCheat is linked to {gameroot}/DeadByDaylight/Binaries/EGS/EasyAntiCheat

Tried that for Steam flatpak with Proton-GE-41 and it's not working, playing as Killer says "Disconnected from the host"

**Comment by aleksasiriski** [comment]
I believe that you're the only guy that has this game still working idk how... Would love to test the Epic Games version but don't want to spend any more money on this game lol

**Comment by Gustash** [comment]
I am not sure how yours is working. I've done all the same steps you have and mine stopped working at the same time as everyone else started reporting it as not working again...

I really don't know what you have different in your system

**Comment by Etaash-mathamsetty** [comment]
> I am not sure how yours is working. I've done all the same steps you have and mine stopped working at the same time as everyone else started reporting it as not working again...
> 
> I really don't know what you have different in your system

Did you link the steam eac runtime to the heroic one and enable the runtime in the heroic settings ?

**Comment by Gustash** [comment]
> > I am not sure how yours is working. I've done all the same steps you have and mine stopped working at the same time as everyone else started reporting it as not working again...
> > 
> > I really don't know what you have different in your system
> 
> Did you link the steam eac runtime to the heroic one and enable the runtime in the heroic settings ?
> I feel like that's the key 

I have not. Not sure why that would make a difference, but I'll try it out tomorrow and report here

**Comment by aleksasiriski** [comment]
Does anyone know how to comment on this thread, I've registered but there's no "comment" button? I wanted to link this issue as proof that it may work for someone (and on Arch, not SteamOS).

**Comment by aleksasiriski** [comment]
> > > I am not sure how yours is working. I've done all the same steps you have and mine stopped working at the same time as everyone else started reporting it as not working again...
> > > I really don't know what you have different in your system
> > 
> > 
> > Did you link the steam eac runtime to the heroic one and enable the runtime in the heroic settings ?
> > I feel like that's the key
> 
> I have not. Not sure why that would make a difference, but I'll try it out tomorrow and report here

Did you test it?

**Comment by Gustash** [comment]
Just noticed that at some point I had re-installed Proton EasyAntiCheat Runtime to a different path, so that's probably why it stopped working on Heroic for me.

I followed the same original steps:

- Unchecked EAC Runtime on Heroic
- Set PROTON_EAC_RUNTIME env var to the path of Steam Proton EAC Runtime
- Symlinked EasyAntiCheat folder to DeadByDaylight/Binaries/EGS

I was able to play a full game, then to make sure I closed the game and was able to play a second full game. So it does seem like the Epic Games version is still Playable at the moment.

**Comment by Etaash-mathamsetty** [comment]
> Just noticed that at some point I had re-installed Proton EasyAntiCheat Runtime to a different path, so that's probably why it stopped working on Heroic for me.
> 
> I followed the same original steps:
> 
> - Unchecked EAC Runtime on Heroic
> - Set PROTON_EAC_RUNTIME env var to the path of Steam Proton EAC Runtime
> - Symlinked EasyAntiCheat folder to DeadByDaylight/Binaries/EGS
> 
> I was able to play a full game, then to make sure I closed the game and was able to play a second full game. So it does seem like the Epic Games version is still Playable at the moment.

See, I wasn't the only one
Unfortunately the heroic toggle won't work until lutris decides to update the runtime on their servers, but you can make a symlink to use the built-in toggle for now

**Comment by aleksasiriski** [comment]
I found a friend with DBD on Epic, I'll test it now.

Gustash, what distro do you use and is Heroic in flatpak or not?

**Comment by Gustash** [comment]
No, I tried removing the v2 folder inside Heroic EAC runtime and symlinking the v2 folder from Steam EAC Runtime there instead. Wouldn't even load me in the menu, not sure why. I did remove the PROTON_EAC_RUNTIME env var when testing, to make sure it wouldn't be a false positive.

Either way, setting the ENV var and untoggling EAC from Heroic works fine

**Comment by Gustash** [comment]
> I found a friend with DBD on Epic, I'll test it now.
> 
> Gustash, what distro do you use and is Heroic in flatpak or not?

Arch Linux, non-flatpak Heroic, just using the AUR `heroic-games-launcher-bin` package

**Comment by Etaash-mathamsetty** [comment]
> No, I tried removing the v2 folder inside Heroic EAC runtime and symlinking the v2 folder from Steam EAC Runtime there instead. Wouldn't even load me in the menu, not sure why. I did remove the PROTON_EAC_RUNTIME env var when testing, to make sure it wouldn't be a false positive.
> 
> Either way, setting the ENV var and untoggling EAC from Heroic works fine

strange, maybe you just forgot to enable the runtime or something ?
I am not using the flatpak as well, im using the official pacman package

**Comment by Gustash** [comment]
No, I certainly toggled it on. Not sure why it didn't work, but no bother

**Comment by aleksasiriski** [comment]
I had to disable `EasyAntiCheat Runtime` in Heroic and add `PROTON_EAC_RUNTIME=/var/home/<user>/.var/app/com.valvesoftware.Steam/data/Steam/steamapps/common/Proton EasyAntiCheat Runtime`.

It works.

**Comment by Etaash-mathamsetty** [comment]
@Curve, maybe update it back to running?

**Comment by Curve** [comment]
> @Curve, maybe update it back to running?

Will do.

**Comment by aleksasiriski** [comment]
> > @Curve, maybe update it back to running?
> 
> Will do.

As a reference add this discussion, and keep "Only on Heroic"

**Comment by indigobo** [comment]
> Symlinked EasyAntiCheat folder to DeadByDaylight/Binaries/EGS/EasyAntiCheat
> 
> I had to disable `EasyAntiCheat Runtime` in Heroic and add `PROTON_EAC_RUNTIME=/var/home/<user>/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Proton EasyAntiCheat Runtime`.
> 
> It works. Played a full match.

What EAC folder did you symlink? I'm still learning about this

**Comment by suzaku1221** [comment]
> > > > @Etaash-mathamsetty were you able to test this on your side?
> > > 
> > > 
> > > yes, the game is still working, played another full game (after 6.4.1 update)
> > 
> > 
> > Can you list all the modifications you made to make the game work?
> 
> firstly I used heroic then you have to link the easy anti cheat folder from the `root directory of the game ( gonna call this {gameroot}. )` to `{gameroot}/DeadByDaylight/Binaries/EGS/EasyAntiCheat` (I used dolphin and just dragged the folder there and pressed 'link') then to use the builtin EAC checkbox, you have to link `~/.config/heroic/tools/runtimes/eac_runtime/v2` to `~/.steam/root/steamapps/common/Proton EasyAntiCheat Runtime/v2` (I used dolphin for this as well, by deleting the v2 folder in heroic and dragging it and pressing link) then install the game, enable the EAC runtime (if on heroic 2.5.0, it should be automatically enabled, if not please tell me, I might have to fix that feature), then enjoy the game (I have played as the killer both times, maybe it disconnects if you play survivor?)
> 
> settings: proton-ge-7-41, ESYNC=on, FSYNC=on, RADV_DEBUG=hang (gpu resets happen randomly for me in this game, this env fixes it)

I am not sure I quite understand how to do the link stuff on Steam Deck, but I will try this and see if it works cause I been dying to play DBD on my Deck ever since I got it

**Comment by Etaash-mathamsetty** [comment]
on heroic/lutris you no longer have to use `PROTON_EAC_RUNTIME` workaround for dead by daylight, lutris has finally updated their runtime

**Comment by aleksasiriski** [comment]
> on heroic/lutris you no longer have to use env variable `PROTON_EAC_RUNTIME` workaround for dead by daylight, lutris has finally updated their runtime, so you can use the builtin checkbox

I still have to use `PROTON_EAC_RUNTIME` with latest Proton GE, tried Wine-Ge as well with no success
