### ISSUE TITLE
Dauntless status update, now Broken

### ISSUE THREAD

**Issue by Feyko** [Starz0r/AreWeAntiCheatYet#993]
### Game Title

Dauntless

### Status of the Anti-Cheat

😥 Broken

### Tinkering Steps

The workaround listed (https://www.reddit.com/r/linux_gaming/comments/wrok4z/dauntless_is_working_again_on_linux/) still works to get in game but as reported by the OP and after extensive testing on my end, the game is still broken and crashes at random intervals :(

### Proof of Mention

None. Multiple people in the link above say the same thing, as do people in the Dauntless Discord. It's also easily reproducible

**Comment by Curve** [comment]
What about https://www.reddit.com/r/linux_gaming/comments/wrok4z/comment/iysi4md/ ?

**Comment by Feyko** [comment]
I've tried that too, though not with the same breadth of runners as when I tested without. The FSR strength could also somehow play a role. I'll do some more testing on my end and contact that person to know what settings they use

**Comment by Feyko** [comment]
Talked with the author of the comment you linked and tried different settings, could not get it to work. But they did confirm it was still working for them :thinking:

**Comment by Etaash-mathamsetty** [comment]
> Talked with the author of the comment you linked and tried different settings, could not get it to work. But they did confirm it was still working for them thinking

maybe just delete your wine prefix and regenerate it

**Comment by Feyko** [comment]
Trust me, I've tried many times. I've tried with at least a dozen runners, trying with/without esync/fsync and async dxvk for many of them, regenerating the prefix each time

**Comment by Etaash-mathamsetty** [comment]
> Trust me, I've tried many times. I've tried with at least a dozen runners, trying with/without esync/fsync and async dxvk for many of them, regenerating the prefix each time

reinstall the EAC runtime and maybe try heroic ?

**Comment by Feyko** [comment]
I'm already using Heroic, as mentioned above
At this point I'm honestly fairly certain Dauntless just can't work on my (and multiple others') system. I've tried all the basic debugging steps you can think of :smile:
